LocalSocket /run/clamav/clamd.ctl
LocalSocketMode 660
User clamav
DatabaseDirectory /var/lib/clamav
Foreground yes
MaxFileSize 10M
MaxScanSize 50M
StreamMaxLength 10M
MaxScanTime 30000
AlertEncrypted yes
AlertExceedsMax yes
LogFile /dev/stderr
