import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url);const ts=require('typescript');const sql=new DatabaseSync(':memory:');for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+name,'utf8').replaceAll('--> statement-breakpoint',''));
const statement=(query,args=[])=>({bind(...a){return statement(query,a)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}});
const stored=new Map();globalThis.auditTestEnv={DB:{prepare:statement,async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}},BUCKET:{async put(k,v){stored.set(k,v)},async get(k){return stored.has(k)?{body:stored.get(k)}:null},async delete(k){stored.delete(k)}}};
globalThis.auditTestUser={userId:'owner-one',email:'test@example.invalid',displayName:'Test auditor'};
const moduleURL=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022})).toString('base64');
const helper=moduleURL(readFileSync('lib/audit.ts','utf8').replace("import { env } from 'cloudflare:workers';","const env=globalThis.auditTestEnv;"));
const permissions=moduleURL(readFileSync('lib/access.ts','utf8').replace("'./audit'",JSON.stringify(helper)));
const transactions=moduleURL(readFileSync('lib/transaction-checks.ts','utf8'));
const auth=moduleURL('export async function getChatGPTUser(){return globalThis.auditTestUser}');
const route=await import(moduleURL(readFileSync('app/api/workspace/route.ts','utf8').replace("'zod'",JSON.stringify(pathToFileURL(require.resolve('zod')).href)).replace("'../../chatgpt-auth'",JSON.stringify(auth)).replace("'../../../lib/audit'",JSON.stringify(helper)).replace("'../../../lib/access'",JSON.stringify(permissions))));
const post=body=>route.POST(new Request('https://audit.test/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://audit.test'},body:JSON.stringify(body)}));
assert.equal((await post({action:'create'})).status,400);
let r=await post({action:'create',entity:'Test Institution',title:'Test audit',lead:'Auditor',due:'2026-12-01',type:'Compliance',scope:'Review sample procurement records.'});assert.equal(r.status,200);const {id}=await r.json();let ws=await (await route.GET()).json();assert.equal(ws.audits.length,1);
assert.equal((await post({action:'status',auditId:id,status:'Issued'})).status,409);
assert.equal((await post({action:'finding',auditId:id,title:'Missing approval',severity:'High',condition:'Test observation',recommendation:'Provide the approval record.'})).status,200);
ws=await (await route.GET()).json();const findingId=ws.audits[0].findings[0].id;
assert.equal((await post({action:'approve',auditId:id,findingId})).status,403);
const form=new FormData();form.set('auditId',id);form.set('file',new File(['Supporting test evidence'],'approval.txt',{type:'text/plain'}));assert.equal((await route.POST(new Request('https://audit.test/api/workspace',{method:'POST',body:form}))).status,200);
ws=await (await route.GET()).json();assert.equal(ws.evidence.length,1);assert.equal(ws.evidence[0].hash.length,64);assert.equal(stored.size,1);const evidenceId=ws.evidence[0].id;
assert.equal((await post({action:'link',auditId:id,findingId,evidenceId})).status,200);
assert.equal((await post({action:'approve',auditId:id,findingId})).status,403);
assert.equal((await post({action:'member',email:'reviewer@example.invalid',name:'Independent Reviewer',role:'Reviewer'})).status,200);
const ownerUser=globalThis.auditTestUser;
globalThis.auditTestUser={userId:'reviewer-id',email:'reviewer@example.invalid',displayName:'Reviewer'};
assert.equal((await (await route.GET()).json()).role,'Reviewer');
assert.equal((await post({action:'finding',auditId:id,title:'Blocked',condition:'Test',recommendation:'Test',severity:'High'})).status,403);
assert.equal((await post({action:'approve',auditId:id,findingId})).status,200);
globalThis.auditTestUser=ownerUser;
for(const status of ['Fieldwork','Review'])assert.equal((await post({action:'status',auditId:id,status})).status,200);
assert.equal((await post({action:'review',auditId:id})).status,403);
assert.equal((await post({action:'status',auditId:id,status:'Issued'})).status,409);
globalThis.auditTestUser={userId:'reviewer-id',email:'reviewer@example.invalid',displayName:'Reviewer'};
assert.equal((await post({action:'review',auditId:id})).status,200);
globalThis.auditTestUser=ownerUser;
assert.equal((await post({action:'status',auditId:id,status:'Issued'})).status,200);
assert.equal((await post({action:'finding',auditId:id,title:'Late change',severity:'Low',condition:'Test',recommendation:'Test'})).status,409);
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,409);
assert.equal((await post({action:'respond',auditId:id,findingId,response:'Approval provided and corrective action recorded.'})).status,200);
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,409);
assert.equal((await post({action:'followPlan',auditId:id,findingId,officer:'Finance Officer',due:'2026-02-30',correctiveAction:'File approval records.'})).status,400);
assert.equal((await post({action:'followPlan',auditId:id,findingId,officer:'Finance Officer',due:'2026-12-10',correctiveAction:'File approval records.',progress:'Records located.'})).status,200);
assert.equal((await post({action:'followSubmit',auditId:id,findingId,progress:'Completed.'})).status,400);
assert.equal((await route.POST(new Request('https://audit.test/api/workspace',{method:'POST',body:form}))).status,409);
const completionForm=new FormData();completionForm.set('auditId',id);completionForm.set('purpose','followup');completionForm.set('findingId',findingId);completionForm.set('file',new File(['Verified corrective action evidence'],'completion.txt',{type:'text/plain'}));assert.equal((await route.POST(new Request('https://audit.test/api/workspace',{method:'POST',body:completionForm}))).status,200);
ws=await (await route.GET()).json();const completionEvidence=ws.evidence.find(e=>e.name==='completion.txt').id;
assert.equal((await post({action:'followSubmit',auditId:id,findingId,progress:'Approval record filed.',evidenceId:completionEvidence})).status,200);
assert.equal((await post({action:'followReview',auditId:id,findingId,decision:'verify',reviewNote:'Self review blocked.'})).status,403);
assert.equal((await post({action:'followPlan',auditId:id,findingId,officer:'Finance Officer',due:'2026-12-10',correctiveAction:'Cannot edit while awaiting review.'})).status,409);
globalThis.auditTestUser={userId:'reviewer-id',email:'reviewer@example.invalid',displayName:'Reviewer'};
assert.equal((await post({action:'followReview',auditId:id,findingId,decision:'return',reviewNote:'Add the signed authorisation record.'})).status,200);
globalThis.auditTestUser=ownerUser;
assert.equal((await post({action:'followSubmit',auditId:id,findingId,progress:'Signed authorisation included.',evidenceId:completionEvidence})).status,200);
globalThis.auditTestUser={userId:'reviewer-id',email:'reviewer@example.invalid',displayName:'Reviewer'};
assert.equal((await post({action:'followReview',auditId:id,findingId,decision:'verify',reviewNote:'Checked the signed authorisation and completion record.'})).status,200);
assert.equal((await post({action:'followReview',auditId:id,findingId,decision:'reopen',reviewNote:'Further reconciliation required.'})).status,200);
globalThis.auditTestUser=ownerUser;
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,409);
assert.equal((await post({action:'followSubmit',auditId:id,findingId,progress:'Reconciliation completed.',evidenceId:completionEvidence})).status,200);
globalThis.auditTestUser={userId:'reviewer-id',email:'reviewer@example.invalid',displayName:'Reviewer'};
assert.equal((await post({action:'followReview',auditId:id,findingId,decision:'verify',reviewNote:'Reconciliation confirmed against evidence.'})).status,200);
globalThis.auditTestUser=ownerUser;ws=await (await route.GET()).json();assert.equal(ws.audits[0].findings[0].followUp.status,'Verified');assert.equal(ws.audits[0].findings[0].followUp.history.length,8);
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,200);
assert.equal((await post({action:'followPlan',auditId:id,findingId,officer:'Test',due:'2026-12-10',correctiveAction:'Closed audit locked.'})).status,409);
const evidenceRoute=await import(moduleURL(readFileSync('app/api/evidence/[id]/route.ts','utf8').replace("'../../../chatgpt-auth'",JSON.stringify(auth)).replace("'../../../../lib/audit'",JSON.stringify(helper)).replace("'../../../../lib/access'",JSON.stringify(permissions))));
assert.equal(await (await evidenceRoute.GET(null,{params:Promise.resolve({id:evidenceId})})).text(),'Supporting test evidence');
globalThis.auditTestUser={userId:'owner-two',email:'other@example.invalid',displayName:'Other'};
assert.equal((await route.GET()).status,403);
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,403);
assert.equal((await evidenceRoute.GET(null,{params:Promise.resolve({id:evidenceId})})).status,403);
globalThis.auditTestUser=ownerUser;
const csv='Date,Reference,Payee,Amount,Invoice,Approval\n2026-10-01,P1,A,10,I1,yes\n2026-10-01,P1,A,10,I1,yes\n2026-10-02,P3,B,20,,yes\n2026-10-02,P4,C,15,I4,yes\n2026-10-03,P5,D,300000,I5,\n';
const {analyseCSV,parseCSV}=await import(transactions);const result=analyseCSV(csv,100000,5);
assert.equal(result.summary.rows,5);assert.equal(result.summary.total,300055);for(const rule of ['Duplicate reference','Possible repeated payment','Missing records','Large amount','Amount outlier'])assert.ok(result.exceptions.some(f=>f.rule===rule));
assert.equal(parseCSV('a,b\n"one,two","line1\nline2"')[1][1],'line1\nline2');assert.throws(()=>analyseCSV('x,y\n1,2'));assert.throws(()=>parseCSV('a,b\n"unclosed'));
const checkRoute=await import(moduleURL(readFileSync('app/api/checks/route.ts','utf8').replace("'../../chatgpt-auth'",JSON.stringify(auth)).replace("'../../../lib/access'",JSON.stringify(permissions)).replace("'../../../lib/audit'",JSON.stringify(helper)).replace("'../../../lib/transaction-checks'",JSON.stringify(transactions))));
const newCase=await (await post({action:'create',entity:'Check Institution',title:'Transactions',lead:'Auditor',due:'2026-12-01',type:'Financial',scope:'Check transaction data.'})).json();const checkForm=new FormData();checkForm.set('auditId',newCase.id);checkForm.set('file',new File([csv],'transactions.csv',{type:'text/csv'}));checkForm.set('largeAmount','100000');checkForm.set('medianFactor','5');const checked=await checkRoute.POST(new Request('https://audit.test/api/checks',{method:'POST',body:checkForm}));assert.equal(checked.status,200);const checkId=(await checked.json()).id;ws=await (await route.GET()).json();assert.equal(ws.checks.length,1);const exceptionId=ws.checks[0].exceptions[0].id;assert.equal((await post({action:'checkFinding',auditId:newCase.id,checkId,exceptionId})).status,200);assert.equal((await post({action:'checkFinding',auditId:newCase.id,checkId,exceptionId})).status,409);
assert.equal((await post({action:'member',email:'viewer@example.invalid',name:'Reader',role:'Viewer'})).status,200);globalThis.auditTestUser={userId:'viewer-id',email:'viewer@example.invalid',displayName:'Reader'};assert.equal((await route.GET()).status,200);assert.equal((await post({action:'samples'})).status,403);globalThis.auditTestUser=ownerUser;assert.equal((await post({action:'member',email:'viewer@example.invalid',name:'Reader',role:'Viewer',active:'no'})).status,200);globalThis.auditTestUser={userId:'viewer-id',email:'viewer@example.invalid',displayName:'Reader'};assert.equal((await route.GET()).status,403);
globalThis.auditTestUser=null;assert.equal((await route.GET()).status,401);assert.equal((await post({action:'samples'})).status,401);
console.log('PASS: workflow, evidence, role permissions, independent approvals, viewer access, revoked membership, CSV parsing and checks, source-linked exception conversion, completion evidence on issued audits, follow-up return/verify/reopen history, self-verification rejection and verified-closure gates.');
