import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url);const ts=require('typescript');const sql=new DatabaseSync(':memory:');for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')))sql.exec(readFileSync('drizzle/'+name,'utf8').replaceAll('--> statement-breakpoint',''));
const statement=(query,args=[])=>({bind(...a){return statement(query,a)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}});
const stored=new Map();globalThis.auditTestEnv={DB:{prepare:statement,async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}},BUCKET:{async put(k,v){stored.set(k,v)},async get(k){return stored.has(k)?{body:stored.get(k)}:null},async delete(k){stored.delete(k)}}};
globalThis.auditTestUser={userId:'owner-one',email:'test@example.invalid',displayName:'Test auditor'};
const moduleURL=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpile(s,{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022})).toString('base64');
const helper=moduleURL(readFileSync('lib/audit.ts','utf8').replace("import { env } from 'cloudflare:workers';","const env=globalThis.auditTestEnv;"));
const auth=moduleURL('export async function getChatGPTUser(){return globalThis.auditTestUser}');
const route=await import(moduleURL(readFileSync('app/api/workspace/route.ts','utf8').replace("'zod'",JSON.stringify(pathToFileURL(require.resolve('zod')).href)).replace("'../../chatgpt-auth'",JSON.stringify(auth)).replace("'../../../lib/audit'",JSON.stringify(helper))));
const post=body=>route.POST(new Request('https://audit.test/api/workspace',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://audit.test'},body:JSON.stringify(body)}));
assert.equal((await post({action:'create'})).status,400);
let r=await post({action:'create',entity:'Test Institution',title:'Test audit',lead:'Auditor',due:'2026-12-01',type:'Compliance',scope:'Review sample procurement records.'});assert.equal(r.status,200);const {id}=await r.json();let ws=await (await route.GET()).json();assert.equal(ws.audits.length,1);
assert.equal((await post({action:'status',auditId:id,status:'Issued'})).status,409);
assert.equal((await post({action:'finding',auditId:id,title:'Missing approval',severity:'High',condition:'Test observation',recommendation:'Provide the approval record.'})).status,200);
ws=await (await route.GET()).json();const findingId=ws.audits[0].findings[0].id;
assert.equal((await post({action:'approve',auditId:id,findingId})).status,409);
const form=new FormData();form.set('auditId',id);form.set('file',new File(['Supporting test evidence'],'approval.txt',{type:'text/plain'}));assert.equal((await route.POST(new Request('https://audit.test/api/workspace',{method:'POST',body:form}))).status,200);
ws=await (await route.GET()).json();assert.equal(ws.evidence.length,1);assert.equal(ws.evidence[0].hash.length,64);assert.equal(stored.size,1);const evidenceId=ws.evidence[0].id;
assert.equal((await post({action:'link',auditId:id,findingId,evidenceId})).status,200);
assert.equal((await post({action:'approve',auditId:id,findingId})).status,200);
for(const status of ['Fieldwork','Review','Issued'])assert.equal((await post({action:'status',auditId:id,status})).status,200);
assert.equal((await post({action:'finding',auditId:id,title:'Late change',severity:'Low',condition:'Test',recommendation:'Test'})).status,409);
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,409);
assert.equal((await post({action:'respond',auditId:id,findingId,response:'Approval provided and corrective action recorded.'})).status,200);
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,200);
const evidenceRoute=await import(moduleURL(readFileSync('app/api/evidence/[id]/route.ts','utf8').replace("'../../../chatgpt-auth'",JSON.stringify(auth)).replace("'../../../../lib/audit'",JSON.stringify(helper))));
assert.equal(await (await evidenceRoute.GET(null,{params:Promise.resolve({id:evidenceId})})).text(),'Supporting test evidence');
globalThis.auditTestUser={userId:'owner-two',email:'other@example.invalid',displayName:'Other'};
assert.equal((await (await route.GET()).json()).audits.length,0);
assert.equal((await post({action:'status',auditId:id,status:'Closed'})).status,404);
assert.equal((await evidenceRoute.GET(null,{params:Promise.resolve({id:evidenceId})})).status,404);
globalThis.auditTestUser=null;assert.equal((await route.GET()).status,401);assert.equal((await post({action:'samples'})).status,401);
console.log('PASS: create, validation, evidence upload/download/hash, evidence-linked approval, stage gates, response and closure, owner isolation and authentication.');
