'use client';
import { useEffect, useRef, useState } from 'react';
import { ShieldCheck, LayoutDashboard, ClipboardList, Files, Flag, FileText, History, Plus, Search, ChevronRight, Download, X, Check, Upload, LockKeyhole, CalendarDays, CircleCheck, LoaderCircle, Menu } from 'lucide-react';
import type { Audit, Finding } from '../lib/audit';
import type { CheckResult } from '../lib/transaction-checks';
type Evidence={id:string;auditId:string;name:string;type:string;hash:string;created:string};
type Event={auditId:string;description:string;created:string};
type Member={email:string;name:string;role:string;active:string};
type Workspace={user:string;email:string;role:string;ownerEmail:string;canWrite:boolean;canReview:boolean;members:Member[];checks:CheckResult[];audits:Audit[];evidence:Evidence[];history:Event[]};
const stages=['Planning','Fieldwork','Review','Issued','Closed'];
const nav=[['Overview',LayoutDashboard],['Audits',ClipboardList],['Evidence',Files],['Findings',Flag],['Checks',ShieldCheck],['Reports',FileText],['Team',CircleCheck],['Activity',History]] as const;
const date=(s:string)=>new Date(s.length===10?s+'T12:00:00Z':s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
function Badge({children}:{children:React.ReactNode}){return <span className={'badge '+String(children).toLowerCase().replaceAll(' ','-')}>{children}</span>}
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function esc(s:string){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
export default function Home(){
 const [ws,setWs]=useState<Workspace>({user:'',email:'',role:'Viewer',ownerEmail:'',canWrite:false,canReview:false,members:[],checks:[],audits:[],evidence:[],history:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [view,setView]=useState('Overview');const [selected,setSelected]=useState('');const [tab,setTab]=useState('Summary');const [query,setQuery]=useState('');const [filter,setFilter]=useState('All stages');const [modal,setModal]=useState('');const [target,setTarget]=useState<Finding|null>(null);const [mobile,setMobile]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 const audit=ws.audits.find(a=>a.id===selected);const findings=ws.audits.flatMap(a=>a.findings.map(f=>({...f,audit:a})));const active=ws.audits.filter(a=>!['Issued','Closed'].includes(a.status));const high=findings.filter(f=>['High','Critical'].includes(f.severity)&&!f.response);const overdue=active.filter(a=>a.due<new Date().toISOString().slice(0,10));
 async function load(){try{const r=await fetch('/api/workspace');const data=await r.json() as Workspace & {error?:string};if(!r.ok)throw new Error(data.error);setWs(data);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load workspace')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 async function action(payload:object|FormData,message='Saved successfully'){setBusy(true);setError('');try{const r=await fetch(modal==='checks'?'/api/checks':'/api/workspace',{method:'POST',...(payload instanceof FormData?{body:payload}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})});const data=await r.json() as {error?:string;id?:string};if(!r.ok)throw new Error(data.error);await load();setModal('');setNotice(message);if(data.id&&!(payload instanceof FormData)){setSelected(data.id);setView('Audits');setTab('Summary')}return true}catch(e){setError(e instanceof Error?e.message:'Unable to save');return false}finally{setBusy(false)}}
 function openAudit(a:Audit){setSelected(a.id);setView('Audits');setTab('Summary')}
 function navigate(v:string){setView(v);setSelected('');setMobile(false);setQuery('')}
 function showModal(name:string,f:Finding|null=null){setError('');setTarget(f);setModal(name)}
 function report(a:Audit){const ev=ws.evidence.filter(e=>e.auditId===a.id);return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(a.reference)} Audit Report</title><style>body{font:16px/1.6 Arial;color:#172c42;max-width:850px;margin:48px auto;padding:24px}h1{font-size:30px}h2{border-bottom:1px solid #ddd;padding-bottom:8px}small{color:#555}.tag{background:#eef3f5;padding:6px 12px}article{page-break-inside:avoid;border-bottom:1px solid #ddd;margin-bottom:24px;padding-bottom:16px}@media print{body{margin:0}button{display:none}}</style></head><body><span class="tag">${a.status==='Issued'||a.status==='Closed'?'ISSUED REPORT':'DRAFT — FOR REVIEW'}${a.sample?' · DEMONSTRATION DATA':''}</span><h1>${esc(a.title)}</h1><p>${esc(a.entity)}<br>${esc(a.reference)} · ${esc(a.type)} audit<br>Audit lead: ${esc(a.lead)} · Due: ${esc(date(a.due))}</p><h2>Audit scope</h2><p>${esc(a.scope)}</p><h2>Findings and recommendations</h2>${a.findings.length?a.findings.map((f,i)=>`<article><h3>${i+1}. ${esc(f.title)}</h3><p>Risk: ${esc(f.severity)} · ${f.approved?'Approved by '+esc(f.approvedBy||'Legacy approval — review required'):'Awaiting independent approval'}</p><p><strong>Observation</strong><br>${esc(f.condition)}</p><p><strong>Recommendation</strong><br>${esc(f.recommendation)}</p><p><strong>Institution response</strong><br>${esc(f.response||'Awaiting response')}</p><p><strong>Evidence</strong><br>${esc(ev.find(e=>e.id===f.evidenceId)?.name||'No supporting evidence linked')}</p>${f.due?`<p>Action due: ${esc(date(f.due))}</p>`:''}</article>`).join(''):'<p>No findings recorded. This alone does not establish audit assurance.</p>'}<h2>Independent review</h2><p>${a.reviewedBy?'Reviewed by '+esc(a.reviewedBy)+' on '+esc(date(a.reviewedAt!)):'Awaiting independent reviewer sign-off.'}</p><h2>Evidence register</h2>${ev.map(e=>`<p>${esc(e.name)}<br><small>SHA-256: ${esc(e.hash)}</small></p>`).join('')||'<p>No evidence uploaded.</p>'}<p><small>Generated ${esc(new Date().toLocaleString('en-GB'))}. Report status reflects the workspace record. Institutional review and formal authorisation are required before external use.</small></p></body></html>`}
 function exportCSV(){const rows=[['Reference','Institution','Title','Type','Status','Lead','Due date','Findings','Evidence'],...ws.audits.map(a=>[a.reference,a.entity,a.title,a.type,a.status,a.lead,a.due,String(a.findings.length),String(ws.evidence.filter(e=>e.auditId===a.id).length)])];download('audit-register.csv',rows.map(r=>r.map(s=>'"'+(/^[=+@-]/.test(s)?"'":'')+s.replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8')}
 function renderEvidenceList({items}:{items:Evidence[]}){return items.length?<div className="file-list">{items.map(e=><a key={e.id} href={'/api/evidence/'+e.id} className="file"><span className="file-icon"><FileText size={20}/></span><span><strong>{e.name}</strong><small>{date(e.created)} · SHA-256 fingerprint recorded</small></span><Download size={18}/></a>)}</div>:<div className="empty small"><Files/><h3>No evidence uploaded</h3><p>Add supporting documents to the audit file.</p></div>}
 function renderFindingCard({f,a,editable=false}:{f:Finding;a:Audit;editable?:boolean}){return <article className="finding"><div className="finding-heading"><Badge>{f.severity}</Badge><span className="muted">{a.reference}</span>{f.approved&&f.approvedBy&&<span className="approved"><CircleCheck size={15}/> Approved</span>}</div><h3>{f.title}</h3><p>{f.condition}</p><div className="recommendation"><strong>Recommendation</strong><p>{f.recommendation}</p></div><div className="finding-meta"><span>{f.evidenceId?'Supporting evidence linked':'Evidence required'}{f.due?' · Action due '+date(f.due):''}</span><span>{f.response?'Response recorded':'Awaiting response'}</span></div>{f.response&&<div className="response"><strong>Institution response</strong><p>{f.response}</p></div>}{editable?<div className="actions">{ws.canWrite&&!['Issued','Closed'].includes(a.status)&&<><button onClick={()=>showModal('link',f)}>Link evidence</button></>}{ws.canReview&&(!f.approved||!f.approvedBy)&&!['Issued','Closed'].includes(a.status)&&(f.preparedBy||a.createdBy||ws.ownerEmail)!==ws.email&&<button onClick={()=>void action({action:'approve',auditId:a.id,findingId:f.id},'Finding independently approved')} disabled={busy}>Approve finding</button>}{ws.canWrite&&a.status!=='Closed'&&<button onClick={()=>showModal('response',f)}>{f.response?'Update response':'Record response'}</button>}</div>:<button className="text-button" onClick={()=>{openAudit(a);setTab('Findings')}}>Open audit <ChevronRight size={15}/></button>}</article>}
 function renderAuditTable(){const items=ws.audits.filter(a=>(a.entity+' '+a.reference+' '+a.title).toLowerCase().includes(query.toLowerCase())&&(filter==='All stages'||a.status===filter));return <><div className="table-tools"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search institutions, audits or references" aria-label="Search audits"/></label><select aria-label="Filter by stage" value={filter} onChange={e=>setFilter(e.target.value)}><option>All stages</option>{stages.map(s=><option key={s}>{s}</option>)}</select><button onClick={exportCSV}><Download size={16}/> Export CSV</button></div><div className="table-scroll"><table><thead><tr><th>Audit / institution</th><th>Stage</th><th>Lead</th><th>Due date</th><th>Findings</th><th></th></tr></thead><tbody>{items.map(a=><tr key={a.id}><td><button className="table-title" onClick={()=>openAudit(a)}><small>{a.reference}{a.sample?' · SAMPLE':''}</small><strong>{a.title}</strong><span>{a.entity}</span></button></td><td><Badge>{a.status}</Badge></td><td>{a.lead}</td><td>{date(a.due)}</td><td>{a.findings.length? <span className="finding-count">{a.findings.length}</span>:'—'}</td><td><button className="icon-button" aria-label={'Open '+a.title} onClick={()=>openAudit(a)}><ChevronRight size={19}/></button></td></tr>)}</tbody></table></div>{!items.length&&<div className="empty"><ClipboardList/><h3>{ws.audits.length?'No matching audits':'Your first audit starts here'}</h3><p>{ws.audits.length?'Try a different search or stage.':'Create an audit or explore the workflow with fictional sample cases.'}</p>{!ws.audits.length&&<div className="actions"><button className="primary" onClick={()=>showModal('audit')}><Plus size={17}/> Create audit</button><button onClick={()=>void action({action:'samples'},'Sample audits loaded')} disabled={busy}>Load sample audits</button></div>}</div>}</>}
 function csvTemplate(){download('sample-transactions.csv','Date,Reference,Payee,Amount,Invoice,Approval\r\n2026-10-01,DEMO-P001,Sample Supplier A,2500,INV-001,Approved\r\n2026-10-01,DEMO-P001,Sample Supplier A,2500,INV-001,Approved\r\n2026-10-02,DEMO-P003,Sample Supplier B,1000,,Approved\r\n2026-10-02,DEMO-P004,Sample Supplier C,1800,INV-004,Approved\r\n2026-10-03,DEMO-P005,Sample Supplier D,300000,INV-005,\r\n2026-10-03,DEMO-P006,Sample Supplier E,2200,INV-006,Approved\r\n','text/csv;charset=utf-8')}
 function renderChecks(items:CheckResult[],a?:Audit){return <>{items.map(c=><section className="panel check-panel" key={c.id}><div className="panel-heading"><div><h2>{c.name}</h2><p>{date(c.created)} · {c.createdBy} · SLE only</p></div><a className="download-link" href={'/api/evidence/'+c.evidenceId}><Download size={16}/> Source CSV</a></div><div className="check-summary"><div><small>Transactions</small><strong>{c.summary.rows}</strong></div><div><small>Rows flagged</small><strong>{c.summary.flaggedRows}</strong></div><div><small>Valid positive amounts</small><strong>SLE {c.summary.total.toLocaleString('en-GB')}</strong></div></div><div className="check-rules">Threshold: SLE {c.rules.largeAmount.toLocaleString('en-GB')} · Outlier: {c.rules.medianFactor} × file median, with at least 5 valid positive amounts. Row numbers identify transactions after the header.</div>{c.exceptions.length?<div className="exception-list">{c.exceptions.map(f=><article key={f.id}><div><Badge>{f.severity}</Badge><strong>{f.rule}</strong><span>Transaction {f.rows.join(', ')}</span></div><p>{f.detail}</p><div className="transaction-lines">{c.transactions.filter(t=>f.rows.includes(t.row)).map(t=><span key={t.row}>#{t.row} · {t.reference||'No reference'} · {t.payee||'No payee'} · {t.date||'No date'} · SLE {t.amount?.toLocaleString('en-GB')??'invalid amount'}</span>)}</div>{a&&ws.canWrite&&!['Issued','Closed'].includes(a.status)&&<button disabled={busy||a.findings.some(x=>x.sourceFlag===c.id+':'+f.id)} onClick={()=>void action({action:'checkFinding',auditId:a.id,checkId:c.id,exceptionId:f.id},'Exception recorded as an evidence-linked finding')}>{a.findings.some(x=>x.sourceFlag===c.id+':'+f.id)?'Recorded as finding':'Record as finding'}</button>}</article>)}</div>:<div className="quiet"><CircleCheck/><strong>No exceptions under these rules</strong><p>This does not establish assurance or confirm that all transactions are correct.</p></div>}{!a&&<div className="panel-footer"><button onClick={()=>{const a=ws.audits.find(a=>a.id===c.auditId);if(a){openAudit(a);setTab('Checks')}}}>Open audit checks</button></div>}</section>)}</>}
 return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark"><ShieldCheck size={25}/></span><div>Audit Workspace<small>SIERRA LEONE</small></div></div><div className="workspace-label">AUDIT & ASSURANCE</div><nav>{nav.map(([n,I])=><button key={n} className={view===n?'nav-link active':'nav-link'} onClick={()=>navigate(n)}><I size={19}/>{n}{n==='Findings'&&findings.length>0&&<span className="nav-count">{findings.length}</span>}</button>)}</nav><div className="sidebar-bottom"><LockKeyhole size={17}/><div>Private workspace<small>{ws.role} access · Team roles enabled</small></div></div><div className="profile"><span>HM</span><div>{ws.user||'Your audit workspace'}<small>{ws.role}</small></div></div></aside>
 <div className="main"><header className="topbar"><div className="breadcrumbs"><button className="mobile-menu" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong>{audit&&<><ChevronRight size={14}/><span>{audit.reference}</span></>}</div><div className="top-right"><span className="secure-label"><LockKeyhole size={14}/> Private access</span><span className="avatar">HM</span></div></header><main>
 {error&&<div className="alert" role="alert"><span>{error}</span>{!modal&&<button onClick={()=>void load()}>Retry</button>}</div>}{notice&&<div className="notice" role="status"><Check size={17}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className="page-heading"><div><div className="eyebrow">{audit?'AUDIT CASE FILE':'AUDIT & ASSURANCE'}</div><h1>{audit?audit.title:({Overview:'A clear view of your audits',Audits:'Audit register',Evidence:'Evidence library',Findings:'Findings & recommendations',Checks:'Transaction checks',Team:'Team & permissions',Reports:'Reports',Activity:'Workspace activity'}[view])}</h1><p>{audit?audit.entity:({Overview:'Plan the work. Follow the evidence. Track every action.',Audits:'Every engagement, from planning to follow-up.',Evidence:'Supporting records, securely attached to their audit.',Findings:'Observations, responses and the actions that follow.',Checks:'Traceable checks on transaction records. Exceptions need auditor review.',Team:'Assign responsibilities and maintain independent review.',Reports:'Prepare reports directly from the audit case file.',Activity:'A recorded history of changes to your audits.'}[view])}</p></div><div className="heading-actions">{audit?<button onClick={()=>{setSelected('');setTab('Summary')}}>Back to register</button>:<button className="primary" disabled={!ws.canWrite} onClick={()=>showModal('audit')}><Plus size={18}/> New audit</button>}</div></div>
 {loading?<div className="empty"><LoaderCircle className="spin"/><p>Loading your audit workspace…</p></div>:audit?<>
 <div className="case-banner"><div><span className="reference">{audit.reference}</span><Badge>{audit.status}</Badge>{audit.sample&&<Badge>Sample data</Badge>}</div><span><CalendarDays size={16}/> Due {date(audit.due)} · {audit.lead}</span></div>
 <div className="stage-track">{stages.map((s,i)=><div key={s} className={i<=stages.indexOf(audit.status)?'stage reached':'stage'}><span>{i<stages.indexOf(audit.status)?<Check size={14}/>:i+1}</span>{s}</div>)}</div>
 <div className="case-tabs">{['Summary','Evidence','Findings','Checks','Report'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}{t==='Evidence'&&<span>{ws.evidence.filter(e=>e.auditId===audit.id).length}</span>}{t==='Findings'&&<span>{audit.findings.length}</span>}</button>)}</div>
 {tab==='Summary'&&<div className="case-grid"><section className="panel"><div className="panel-heading"><h2>Engagement overview</h2><Badge>{audit.type}</Badge></div><div className="scope"><h3>Audit scope</h3><p>{audit.scope}</p></div><div className="details"><div><small>Institution</small><strong>{audit.entity}</strong></div><div><small>Audit lead</small><strong>{audit.lead}</strong></div><div><small>Created</small><strong>{date(audit.created)}</strong></div><div><small>Deadline</small><strong>{date(audit.due)}</strong></div></div><div className="panel-footer">{audit.status!=='Closed'?<><p>{audit.reviewedBy?'Independently reviewed by '+audit.reviewedBy+'. ':''}{audit.status==='Review'?'Findings must be approved and supported by evidence before issue.':audit.status==='Issued'?'Record responses to all findings before closing this audit.':'Complete the work for this stage before advancing.'}</p>{audit.status==='Review'&&ws.canReview&&!audit.reviewedBy&&(audit.createdBy||ws.ownerEmail)!==ws.email&&<button disabled={busy} onClick={()=>void action({action:'review',auditId:audit.id},'Audit approved for issue')}>Approve audit for issue</button>}<button className="primary" disabled={busy||!ws.canWrite} onClick={()=>void action({action:'status',auditId:audit.id,status:stages[stages.indexOf(audit.status)+1]},'Audit stage updated')}>Move to {stages[stages.indexOf(audit.status)+1]}</button></>:<p><CircleCheck size={18}/> This audit is closed.</p>}</div></section><section className="panel"><div className="panel-heading"><h2>Case activity</h2><History size={18}/></div><div className="timeline">{ws.history.filter(e=>e.auditId===audit.id).slice(0,6).map((e,i)=><div key={i}><span className="timeline-point"/><strong>{e.description}</strong><small>{date(e.created)}</small></div>)}</div></section></div>}
 {tab==='Evidence'&&<section className="panel"><div className="panel-heading"><div><h2>Supporting evidence</h2><p>Maximum 10 MB per file. Each upload receives a SHA-256 fingerprint.</p></div>{ws.canWrite&&!['Issued','Closed'].includes(audit.status)&&<button className="primary" onClick={()=>showModal('upload')}><Upload size={17}/> Upload evidence</button>}</div>{renderEvidenceList({items:ws.evidence.filter(e=>e.auditId===audit.id)})}</section>}
 {tab==='Findings'&&<><div className="section-heading"><h2>{audit.findings.length} finding{audit.findings.length!==1?'s':''} recorded</h2>{ws.canWrite&&!['Issued','Closed'].includes(audit.status)&&<button className="primary" onClick={()=>showModal('finding')}><Plus size={17}/> Record finding</button>}</div>{audit.findings.map(f=><div key={f.id}>{renderFindingCard({f,a:audit,editable:true})}</div>)}{!audit.findings.length&&<div className="panel empty"><Flag/><h3>No findings recorded</h3><p>Record observations and link the evidence that supports them.</p></div>}</>}
 {tab==='Checks'&&<><div className="section-heading"><div><h2>Transaction checks</h2><p className="muted">Flags are screening exceptions; review the evidence before recording findings.</p></div>{ws.canWrite&&!['Issued','Closed'].includes(audit.status)&&<button className="primary" onClick={()=>showModal('checks')}><Upload size={17}/> Import CSV</button>}</div>{renderChecks(ws.checks.filter(c=>c.auditId===audit.id),audit)}{!ws.checks.some(c=>c.auditId===audit.id)&&<div className="panel empty"><ShieldCheck/><h3>No transaction checks yet</h3><p>Import the audit’s transaction records or try the fictional sample CSV.</p><button onClick={csvTemplate}><Download size={16}/> Download sample CSV</button></div>}</>}
 {tab==='Report'&&<section className="panel report-panel"><div className="panel-heading"><div><h2>Audit report</h2><p>Generated from this audit’s scope, findings and evidence register.</p></div><button className="primary" onClick={()=>download(audit.reference+'-report.html',report(audit),'text/html')}><Download size={17}/> Download report</button></div><iframe title="Audit report preview" srcDoc={report(audit)} sandbox=""/></section>}
 </>:<>
 {view==='Overview'&&<><div className="stats"><div><span>Active audits <ClipboardList size={18}/></span><strong>{active.length}</strong><small>Across all current engagements</small></div><div><span>Findings requiring action <Flag size={18}/></span><strong>{high.length}<em>High / critical</em></strong><small>Without an institution response</small></div><div><span>Evidence collected <Files size={18}/></span><strong>{ws.evidence.length}</strong><small>Documents attached to case files</small></div><div><span>Overdue audits <CalendarDays size={18}/></span><strong>{overdue.length}</strong><small>Open audits past their deadline</small></div></div><div className="overview-grid"><section className="panel priority-panel"><div className="panel-heading"><div><h2>Attention required</h2><p>Open findings with the highest risk.</p></div><span className="count-label">{high.length} open</span></div>{high.length?<div className="priority-list">{high.slice(0,3).map(f=><button key={f.id} onClick={()=>{openAudit(f.audit);setTab('Findings')}}><span className="priority-line"/><div><small>{f.audit.entity}{f.audit.sample?' · SAMPLE':''}</small><strong>{f.title}</strong><span>{f.audit.reference} · {f.due?'Action due '+date(f.due):'Awaiting response'}</span></div><Badge>{f.severity}</Badge><ChevronRight size={17}/></button>)}</div>:<div className="quiet"><CircleCheck size={24}/><strong>No high-risk findings awaiting response</strong><p>New findings will appear here as work progresses.</p></div>}</section><section className="panel pipeline"><div className="panel-heading"><h2>Audit pipeline</h2><ClipboardList size={18}/></div>{stages.map(s=><div className="pipeline-row" key={s}><div><span>{s}</span><strong>{ws.audits.filter(a=>a.status===s).length}</strong></div><div className="bar"><span style={{width:(ws.audits.length?ws.audits.filter(a=>a.status===s).length/ws.audits.length*100:0)+'%'}}/></div></div>)}</section></div><section className="panel register"><div className="panel-heading"><div><h2>Audit register</h2><p>Current engagements and their progress.</p></div><button className="text-button" onClick={()=>navigate('Audits')}>View all audits <ChevronRight size={15}/></button></div>{renderAuditTable()}</section></>}
 {view==='Audits'&&<section className="panel register">{renderAuditTable()}</section>}
 {view==='Evidence'&&<section className="panel"><div className="panel-heading"><h2>{ws.evidence.length} evidence files</h2></div>{renderEvidenceList({items:ws.evidence})}</section>}
 {view==='Findings'&&<>{findings.map(f=><div key={f.id}>{renderFindingCard({f,a:f.audit})}</div>)}{!findings.length&&<div className="panel empty"><Flag/><h3>No findings yet</h3><p>Open an audit case to record a finding.</p></div>}</>}
 {view==='Checks'&&<>{renderChecks(ws.checks)}{!ws.checks.length&&<div className="panel empty"><ShieldCheck/><h3>Check your transaction records</h3><p>Open an audit and choose Checks to import a CSV. The source and screening results stay linked to the case.</p><div className="actions"><button onClick={()=>navigate('Audits')}>Open audit register</button><button onClick={csvTemplate}><Download size={16}/> Download sample CSV</button></div></div>}</>}
 {view==='Team'&&<><div className="team-explainer"><div><h3>Auditor</h3><p>Creates audits, uploads evidence, records findings and responses.</p></div><div><h3>Reviewer</h3><p>Approves another person’s findings and signs off audits for issue.</p></div><div><h3>Viewer</h3><p>Reads case files, evidence, checks and reports.</p></div></div><section className="panel"><div className="panel-heading"><div><h2>Workspace team</h2><p>Role assignment and workspace access are separate. No invitations are sent here.</p></div>{ws.role==='Owner'&&<button className="primary" onClick={()=>showModal('member')}><Plus size={17}/> Add member</button>}</div><div className="team-row"><div><strong>Workspace owner</strong><small>{ws.ownerEmail}</small></div><Badge>Owner</Badge><span>Active</span></div>{ws.members.map(m=><div className="team-row" key={m.email}><div><strong>{m.name}</strong><small>{m.email}</small></div>{ws.role==='Owner'?<select aria-label={'Role for '+m.name} value={m.role} disabled={busy} onChange={e=>void action({action:'member',...m,role:e.target.value},'Team role updated')}><option>Auditor</option><option>Reviewer</option><option>Viewer</option></select>:<Badge>{m.role}</Badge>}{ws.role==='Owner'?<button disabled={busy} onClick={()=>void action({action:'member',...m,active:m.active==='yes'?'no':'yes'},'Member access updated')}>{m.active==='yes'?'Deactivate':'Activate'}</button>:<span>{m.active==='yes'?'Active':'Inactive'}</span>}</div>)}</section><div className="review-note"><LockKeyhole size={18}/><p>Self-approval is blocked. A different authorised reviewer must sign in to approve findings and the audit before it can be issued. Existing owner-only access is preserved.</p></div></>}
 {view==='Reports'&&<div className="reports-grid">{ws.audits.map(a=><section className="panel report-card" key={a.id}><FileText size={27}/><Badge>{['Issued','Closed'].includes(a.status)?'Issued':'Draft'}</Badge><small>{a.reference}{a.sample?' · SAMPLE':''}</small><h2>{a.title}</h2><p>{a.entity}</p><div className="report-info">{a.findings.length} findings · {ws.evidence.filter(e=>e.auditId===a.id).length} evidence files</div><div className="actions"><button onClick={()=>{openAudit(a);setTab('Report')}}>Preview report</button><button aria-label={'Download '+a.reference+' report'} onClick={()=>download(a.reference+'-report.html',report(a),'text/html')}><Download size={17}/></button></div></section>)}{!ws.audits.length&&<div className="panel empty"><FileText/><h3>No reports available</h3><p>Create an audit to begin its report.</p></div>}</div>}
 {view==='Activity'&&<section className="panel"><div className="panel-heading"><h2>Recorded changes</h2><span className="muted">Latest 100 events</span></div><div className="activity-list">{ws.history.map((e,i)=><div key={i}><span className="file-icon"><History size={18}/></span><div><strong>{e.description}</strong><small>{ws.audits.find(a=>a.id===e.auditId)?.reference} · {date(e.created)}</small></div></div>)}{!ws.history.length&&<div className="empty"><History/><h3>No activity yet</h3><p>Your saved changes will be recorded here.</p></div>}</div></section>}
 </>}
 <footer><ShieldCheck size={15}/><span>Audit Workspace · Roles & transaction checks</span><span>Independent review · Evidence-linked checks</span></footer></main></div>
 <dialog ref={dialog} onCancel={()=>{if(!busy)setModal('')}} onClose={()=>setModal('')}><div className="modal-head"><div className="eyebrow">{modal==='audit'?'NEW ENGAGEMENT':'AUDIT CASE FILE'}</div><button aria-label="Close dialog" disabled={busy} onClick={()=>setModal('')}><X size={20}/></button><h2>{{audit:'Create an audit',finding:'Record a finding',upload:'Upload evidence',response:'Institution response',link:'Link supporting evidence',checks:'Import transaction records',member:'Add team member'}[modal]}</h2><p>{modal==='audit'?'Define the engagement before fieldwork begins.':modal==='member'?'Assign an auditor, reviewer or viewer role.':audit?.reference+' · '+audit?.entity}</p></div>{error&&<div className="modal-error" role="alert">{error}</div>}
 <form key={modal} onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const values=Object.fromEntries(data);if(modal==='upload'||modal==='checks'){data.set('auditId',audit!.id);await action(data,modal==='checks'?'Transaction checks completed':'Evidence uploaded securely')}else await action({...values,action:modal==='audit'?'create':modal==='response'?'respond':modal,auditId:audit?.id,findingId:target?.id},modal==='audit'?'Audit created':'Change saved')}}>
 {modal==='audit'&&<><label>Institution<input name="entity" required maxLength={200} placeholder="Institution or department name"/></label><label>Audit title<input name="title" required maxLength={200} placeholder="e.g. Procurement and expenditure review"/></label><div className="form-grid"><label>Audit type<select name="type"><option>Financial</option><option>Compliance</option><option>Performance</option><option>Internal</option></select></label><label>Audit lead<input name="lead" required maxLength={100} placeholder="Lead auditor’s name"/></label></div><label>Deadline<input name="due" type="date" required/></label><label>Scope<textarea name="scope" rows={4} required maxLength={4000} placeholder="What will this audit examine?"/></label></>}
 {modal==='finding'&&<><label>Finding title<input name="title" required maxLength={200}/></label><div className="form-grid"><label>Risk severity<select name="severity"><option>High</option><option>Critical</option><option>Medium</option><option>Low</option></select></label><label>Action deadline<input name="due" type="date"/></label></div><label>Observation<textarea name="condition" required rows={3} maxLength={4000}/></label><label>Recommendation<textarea name="recommendation" required rows={3} maxLength={4000}/></label><label>Supporting evidence<select name="evidenceId"><option value="">Link evidence later</option>{ws.evidence.filter(e=>e.auditId===audit?.id).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></>}
 {modal==='upload'&&<><div className="upload-zone"><Upload size={29}/><strong>Attach a supporting document</strong><span>PDF, Excel, CSV, Word, text or image · Up to 10 MB</span><input name="file" type="file" required accept=".pdf,.csv,.xlsx,.xls,.docx,.txt,.png,.jpg,.jpeg"/></div><p className="muted">Files are stored privately and fingerprinted at upload. Downloads preserve the original file.</p></>}
 {modal==='response'&&<><p className="selected-finding">{target?.title}</p><label>Institution response<textarea name="response" required rows={5} maxLength={4000} defaultValue={target?.response} placeholder="Record the response and corrective action committed."/></label></>}
 {modal==='link'&&<><p className="selected-finding">{target?.title}</p><label>Supporting evidence<select name="evidenceId" required><option value="">Select an uploaded document</option>{ws.evidence.filter(e=>e.auditId===audit?.id).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><p className="muted">Changing supporting evidence requires the finding to be approved again.</p></>}
 {modal==='member'&&<><label>Full name<input name="name" required maxLength={100}/></label><label>Email used to sign in<input name="email" type="email" required maxLength={200}/></label><label>Workspace role<select name="role"><option>Auditor</option><option>Reviewer</option><option>Viewer</option></select></label><p className="muted">This assigns a role without sending an invitation. Grant this person access through the workspace sharing controls before they sign in.</p></>}
 {modal==='checks'&&<><p className="muted">Required columns: Date, Reference, Payee, Amount, Invoice, Approval. Dates use YYYY-MM-DD; amounts use SLE without thousands separators. Maximum 2,000 rows and 512 KB.</p><button type="button" className="template-button" onClick={csvTemplate}><Download size={15}/> Download sample CSV</button><label>Transaction CSV<input name="file" type="file" required accept=".csv,text/csv"/></label><div className="form-grid"><label>Large amount threshold (SLE)<input name="largeAmount" type="number" min="1" max="1000000000000" step="0.01" defaultValue="100000" required/></label><label>Median multiplier<input name="medianFactor" type="number" min="2" max="100" step="0.5" defaultValue="5" required/></label></div><p className="muted">These are configurable screening rules, not legal thresholds or proof of irregularity. The source file is saved as audit evidence.</p></>}
 <div className="modal-actions"><button type="button" disabled={busy} onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>} {busy?'Saving…':modal==='audit'?'Create audit':modal==='upload'?'Upload evidence':'Save'}</button></div></form></dialog>
 </div>
}
