'use client';
import { useEffect, useRef, useState } from 'react';
import { ShieldCheck, LayoutDashboard, ClipboardList, Files, Flag, FileText, History, Plus, Search, ChevronRight, Download, X, Check, Upload, LockKeyhole, CalendarDays, CircleCheck, LoaderCircle, Menu } from 'lucide-react';
import type { Audit, Finding } from '../lib/audit';
type Evidence={id:string;auditId:string;name:string;type:string;hash:string;created:string};
type Event={auditId:string;description:string;created:string};
type Workspace={user:string;audits:Audit[];evidence:Evidence[];history:Event[]};
const stages=['Planning','Fieldwork','Review','Issued','Closed'];
const nav=[['Overview',LayoutDashboard],['Audits',ClipboardList],['Evidence',Files],['Findings',Flag],['Reports',FileText],['Activity',History]] as const;
const date=(s:string)=>new Date(s.length===10?s+'T12:00:00Z':s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
function Badge({children}:{children:React.ReactNode}){return <span className={'badge '+String(children).toLowerCase().replaceAll(' ','-')}>{children}</span>}
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function esc(s:string){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
export default function Home(){
 const [ws,setWs]=useState<Workspace>({user:'',audits:[],evidence:[],history:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [view,setView]=useState('Overview');const [selected,setSelected]=useState('');const [tab,setTab]=useState('Summary');const [query,setQuery]=useState('');const [filter,setFilter]=useState('All stages');const [modal,setModal]=useState('');const [target,setTarget]=useState<Finding|null>(null);const [mobile,setMobile]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 const audit=ws.audits.find(a=>a.id===selected);const findings=ws.audits.flatMap(a=>a.findings.map(f=>({...f,audit:a})));const active=ws.audits.filter(a=>!['Issued','Closed'].includes(a.status));const high=findings.filter(f=>['High','Critical'].includes(f.severity)&&!f.response);const overdue=active.filter(a=>a.due<new Date().toISOString().slice(0,10));
 async function load(){try{const r=await fetch('/api/workspace');const data=await r.json() as Workspace & {error?:string};if(!r.ok)throw new Error(data.error);setWs(data);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load workspace')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 async function action(payload:object|FormData,message='Saved successfully'){setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'POST',...(payload instanceof FormData?{body:payload}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})});const data=await r.json() as {error?:string;id?:string};if(!r.ok)throw new Error(data.error);await load();setModal('');setNotice(message);if(data.id){setSelected(data.id);setView('Audits');setTab('Summary')}return true}catch(e){setError(e instanceof Error?e.message:'Unable to save');return false}finally{setBusy(false)}}
 function openAudit(a:Audit){setSelected(a.id);setView('Audits');setTab('Summary')}
 function navigate(v:string){setView(v);setSelected('');setMobile(false);setQuery('')}
 function showModal(name:string,f:Finding|null=null){setError('');setTarget(f);setModal(name)}
 function report(a:Audit){const ev=ws.evidence.filter(e=>e.auditId===a.id);return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(a.reference)} Audit Report</title><style>body{font:16px/1.6 Arial;color:#172c42;max-width:850px;margin:48px auto;padding:24px}h1{font-size:30px}h2{border-bottom:1px solid #ddd;padding-bottom:8px}small{color:#555}.tag{background:#eef3f5;padding:6px 12px}article{page-break-inside:avoid;border-bottom:1px solid #ddd;margin-bottom:24px;padding-bottom:16px}@media print{body{margin:0}button{display:none}}</style></head><body><span class="tag">${a.status==='Issued'||a.status==='Closed'?'ISSUED REPORT':'DRAFT — FOR REVIEW'}${a.sample?' · DEMONSTRATION DATA':''}</span><h1>${esc(a.title)}</h1><p>${esc(a.entity)}<br>${esc(a.reference)} · ${esc(a.type)} audit<br>Audit lead: ${esc(a.lead)} · Due: ${esc(date(a.due))}</p><h2>Audit scope</h2><p>${esc(a.scope)}</p><h2>Findings and recommendations</h2>${a.findings.length?a.findings.map((f,i)=>`<article><h3>${i+1}. ${esc(f.title)}</h3><p>Risk: ${esc(f.severity)} · ${f.approved?'Approved':'Awaiting approval'}</p><p><strong>Observation</strong><br>${esc(f.condition)}</p><p><strong>Recommendation</strong><br>${esc(f.recommendation)}</p><p><strong>Institution response</strong><br>${esc(f.response||'Awaiting response')}</p><p><strong>Evidence</strong><br>${esc(ev.find(e=>e.id===f.evidenceId)?.name||'No supporting evidence linked')}</p>${f.due?`<p>Action due: ${esc(date(f.due))}</p>`:''}</article>`).join(''):'<p>No findings recorded. This alone does not establish audit assurance.</p>'}<h2>Evidence register</h2>${ev.map(e=>`<p>${esc(e.name)}<br><small>SHA-256: ${esc(e.hash)}</small></p>`).join('')||'<p>No evidence uploaded.</p>'}<p><small>Generated ${esc(new Date().toLocaleString('en-GB'))}. Report status reflects the workspace record. Institutional review and formal authorisation are required before external use.</small></p></body></html>`}
 function exportCSV(){const rows=[['Reference','Institution','Title','Type','Status','Lead','Due date','Findings','Evidence'],...ws.audits.map(a=>[a.reference,a.entity,a.title,a.type,a.status,a.lead,a.due,String(a.findings.length),String(ws.evidence.filter(e=>e.auditId===a.id).length)])];download('audit-register.csv',rows.map(r=>r.map(s=>'"'+(/^[=+@-]/.test(s)?"'":'')+s.replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8')}
 function renderEvidenceList({items}:{items:Evidence[]}){return items.length?<div className="file-list">{items.map(e=><a key={e.id} href={'/api/evidence/'+e.id} className="file"><span className="file-icon"><FileText size={20}/></span><span><strong>{e.name}</strong><small>{date(e.created)} · SHA-256 fingerprint recorded</small></span><Download size={18}/></a>)}</div>:<div className="empty small"><Files/><h3>No evidence uploaded</h3><p>Add supporting documents to the audit file.</p></div>}
 function renderFindingCard({f,a,editable=false}:{f:Finding;a:Audit;editable?:boolean}){return <article className="finding"><div className="finding-heading"><Badge>{f.severity}</Badge><span className="muted">{a.reference}</span>{f.approved&&<span className="approved"><CircleCheck size={15}/> Approved</span>}</div><h3>{f.title}</h3><p>{f.condition}</p><div className="recommendation"><strong>Recommendation</strong><p>{f.recommendation}</p></div><div className="finding-meta"><span>{f.evidenceId?'Supporting evidence linked':'Evidence required'}{f.due?' · Action due '+date(f.due):''}</span><span>{f.response?'Response recorded':'Awaiting response'}</span></div>{f.response&&<div className="response"><strong>Institution response</strong><p>{f.response}</p></div>}{editable?<div className="actions">{!['Issued','Closed'].includes(a.status)&&<><button onClick={()=>showModal('link',f)}>Link evidence</button>{!f.approved&&<button onClick={()=>void action({action:'approve',auditId:a.id,findingId:f.id},'Finding approved')} disabled={busy}>Approve finding</button>}</>}{a.status!=='Closed'&&<button onClick={()=>showModal('response',f)}>{f.response?'Update response':'Record response'}</button>}</div>:<button className="text-button" onClick={()=>{openAudit(a);setTab('Findings')}}>Open audit <ChevronRight size={15}/></button>}</article>}
 function renderAuditTable(){const items=ws.audits.filter(a=>(a.entity+' '+a.reference+' '+a.title).toLowerCase().includes(query.toLowerCase())&&(filter==='All stages'||a.status===filter));return <><div className="table-tools"><label className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search institutions, audits or references" aria-label="Search audits"/></label><select aria-label="Filter by stage" value={filter} onChange={e=>setFilter(e.target.value)}><option>All stages</option>{stages.map(s=><option key={s}>{s}</option>)}</select><button onClick={exportCSV}><Download size={16}/> Export CSV</button></div><div className="table-scroll"><table><thead><tr><th>Audit / institution</th><th>Stage</th><th>Lead</th><th>Due date</th><th>Findings</th><th></th></tr></thead><tbody>{items.map(a=><tr key={a.id}><td><button className="table-title" onClick={()=>openAudit(a)}><small>{a.reference}{a.sample?' · SAMPLE':''}</small><strong>{a.title}</strong><span>{a.entity}</span></button></td><td><Badge>{a.status}</Badge></td><td>{a.lead}</td><td>{date(a.due)}</td><td>{a.findings.length? <span className="finding-count">{a.findings.length}</span>:'—'}</td><td><button className="icon-button" aria-label={'Open '+a.title} onClick={()=>openAudit(a)}><ChevronRight size={19}/></button></td></tr>)}</tbody></table></div>{!items.length&&<div className="empty"><ClipboardList/><h3>{ws.audits.length?'No matching audits':'Your first audit starts here'}</h3><p>{ws.audits.length?'Try a different search or stage.':'Create an audit or explore the workflow with fictional sample cases.'}</p>{!ws.audits.length&&<div className="actions"><button className="primary" onClick={()=>showModal('audit')}><Plus size={17}/> Create audit</button><button onClick={()=>void action({action:'samples'},'Sample audits loaded')} disabled={busy}>Load sample audits</button></div>}</div>}</>}
 return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark"><ShieldCheck size={25}/></span><div>Audit Workspace<small>SIERRA LEONE</small></div></div><div className="workspace-label">AUDIT & ASSURANCE</div><nav>{nav.map(([n,I])=><button key={n} className={view===n?'nav-link active':'nav-link'} onClick={()=>navigate(n)}><I size={19}/>{n}{n==='Findings'&&findings.length>0&&<span className="nav-count">{findings.length}</span>}</button>)}</nav><div className="sidebar-bottom"><LockKeyhole size={17}/><div>Private workspace<small>Owner access · First release</small></div></div><div className="profile"><span>HM</span><div>{ws.user||'Your audit workspace'}<small>Workspace owner</small></div></div></aside>
 <div className="main"><header className="topbar"><div className="breadcrumbs"><button className="mobile-menu" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong>{audit&&<><ChevronRight size={14}/><span>{audit.reference}</span></>}</div><div className="top-right"><span className="secure-label"><LockKeyhole size={14}/> Private access</span><span className="avatar">HM</span></div></header><main>
 {error&&<div className="alert" role="alert"><span>{error}</span>{!modal&&<button onClick={()=>void load()}>Retry</button>}</div>}{notice&&<div className="notice" role="status"><Check size={17}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className="page-heading"><div><div className="eyebrow">{audit?'AUDIT CASE FILE':'AUDIT & ASSURANCE'}</div><h1>{audit?audit.title:({Overview:'A clear view of your audits',Audits:'Audit register',Evidence:'Evidence library',Findings:'Findings & recommendations',Reports:'Reports',Activity:'Workspace activity'}[view])}</h1><p>{audit?audit.entity:({Overview:'Plan the work. Follow the evidence. Track every action.',Audits:'Every engagement, from planning to follow-up.',Evidence:'Supporting records, securely attached to their audit.',Findings:'Observations, responses and the actions that follow.',Reports:'Prepare reports directly from the audit case file.',Activity:'A recorded history of changes to your audits.'}[view])}</p></div><div className="heading-actions">{audit?<button onClick={()=>{setSelected('');setTab('Summary')}}>Back to register</button>:<button className="primary" onClick={()=>showModal('audit')}><Plus size={18}/> New audit</button>}</div></div>
 {loading?<div className="empty"><LoaderCircle className="spin"/><p>Loading your audit workspace…</p></div>:audit?<>
 <div className="case-banner"><div><span className="reference">{audit.reference}</span><Badge>{audit.status}</Badge>{audit.sample&&<Badge>Sample data</Badge>}</div><span><CalendarDays size={16}/> Due {date(audit.due)} · {audit.lead}</span></div>
 <div className="stage-track">{stages.map((s,i)=><div key={s} className={i<=stages.indexOf(audit.status)?'stage reached':'stage'}><span>{i<stages.indexOf(audit.status)?<Check size={14}/>:i+1}</span>{s}</div>)}</div>
 <div className="case-tabs">{['Summary','Evidence','Findings','Report'].map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{t}{t==='Evidence'&&<span>{ws.evidence.filter(e=>e.auditId===audit.id).length}</span>}{t==='Findings'&&<span>{audit.findings.length}</span>}</button>)}</div>
 {tab==='Summary'&&<div className="case-grid"><section className="panel"><div className="panel-heading"><h2>Engagement overview</h2><Badge>{audit.type}</Badge></div><div className="scope"><h3>Audit scope</h3><p>{audit.scope}</p></div><div className="details"><div><small>Institution</small><strong>{audit.entity}</strong></div><div><small>Audit lead</small><strong>{audit.lead}</strong></div><div><small>Created</small><strong>{date(audit.created)}</strong></div><div><small>Deadline</small><strong>{date(audit.due)}</strong></div></div><div className="panel-footer">{audit.status!=='Closed'?<><p>{audit.status==='Review'?'Findings must be approved and supported by evidence before issue.':audit.status==='Issued'?'Record responses to all findings before closing this audit.':'Complete the work for this stage before advancing.'}</p><button className="primary" disabled={busy} onClick={()=>void action({action:'status',auditId:audit.id,status:stages[stages.indexOf(audit.status)+1]},'Audit stage updated')}>Move to {stages[stages.indexOf(audit.status)+1]}</button></>:<p><CircleCheck size={18}/> This audit is closed.</p>}</div></section><section className="panel"><div className="panel-heading"><h2>Case activity</h2><History size={18}/></div><div className="timeline">{ws.history.filter(e=>e.auditId===audit.id).slice(0,6).map((e,i)=><div key={i}><span className="timeline-point"/><strong>{e.description}</strong><small>{date(e.created)}</small></div>)}</div></section></div>}
 {tab==='Evidence'&&<section className="panel"><div className="panel-heading"><div><h2>Supporting evidence</h2><p>Maximum 10 MB per file. Each upload receives a SHA-256 fingerprint.</p></div>{!['Issued','Closed'].includes(audit.status)&&<button className="primary" onClick={()=>showModal('upload')}><Upload size={17}/> Upload evidence</button>}</div>{renderEvidenceList({items:ws.evidence.filter(e=>e.auditId===audit.id)})}</section>}
 {tab==='Findings'&&<><div className="section-heading"><h2>{audit.findings.length} finding{audit.findings.length!==1?'s':''} recorded</h2>{!['Issued','Closed'].includes(audit.status)&&<button className="primary" onClick={()=>showModal('finding')}><Plus size={17}/> Record finding</button>}</div>{audit.findings.map(f=><div key={f.id}>{renderFindingCard({f,a:audit,editable:true})}</div>)}{!audit.findings.length&&<div className="panel empty"><Flag/><h3>No findings recorded</h3><p>Record observations and link the evidence that supports them.</p></div>}</>}
 {tab==='Report'&&<section className="panel report-panel"><div className="panel-heading"><div><h2>Audit report</h2><p>Generated from this audit’s scope, findings and evidence register.</p></div><button className="primary" onClick={()=>download(audit.reference+'-report.html',report(audit),'text/html')}><Download size={17}/> Download report</button></div><iframe title="Audit report preview" srcDoc={report(audit)} sandbox=""/></section>}
 </>:<>
 {view==='Overview'&&<><div className="stats"><div><span>Active audits <ClipboardList size={18}/></span><strong>{active.length}</strong><small>Across all current engagements</small></div><div><span>Findings requiring action <Flag size={18}/></span><strong>{high.length}<em>High / critical</em></strong><small>Without an institution response</small></div><div><span>Evidence collected <Files size={18}/></span><strong>{ws.evidence.length}</strong><small>Documents attached to case files</small></div><div><span>Overdue audits <CalendarDays size={18}/></span><strong>{overdue.length}</strong><small>Open audits past their deadline</small></div></div><div className="overview-grid"><section className="panel priority-panel"><div className="panel-heading"><div><h2>Attention required</h2><p>Open findings with the highest risk.</p></div><span className="count-label">{high.length} open</span></div>{high.length?<div className="priority-list">{high.slice(0,3).map(f=><button key={f.id} onClick={()=>{openAudit(f.audit);setTab('Findings')}}><span className="priority-line"/><div><small>{f.audit.entity}{f.audit.sample?' · SAMPLE':''}</small><strong>{f.title}</strong><span>{f.audit.reference} · {f.due?'Action due '+date(f.due):'Awaiting response'}</span></div><Badge>{f.severity}</Badge><ChevronRight size={17}/></button>)}</div>:<div className="quiet"><CircleCheck size={24}/><strong>No high-risk findings awaiting response</strong><p>New findings will appear here as work progresses.</p></div>}</section><section className="panel pipeline"><div className="panel-heading"><h2>Audit pipeline</h2><ClipboardList size={18}/></div>{stages.map(s=><div className="pipeline-row" key={s}><div><span>{s}</span><strong>{ws.audits.filter(a=>a.status===s).length}</strong></div><div className="bar"><span style={{width:(ws.audits.length?ws.audits.filter(a=>a.status===s).length/ws.audits.length*100:0)+'%'}}/></div></div>)}</section></div><section className="panel register"><div className="panel-heading"><div><h2>Audit register</h2><p>Current engagements and their progress.</p></div><button className="text-button" onClick={()=>navigate('Audits')}>View all audits <ChevronRight size={15}/></button></div>{renderAuditTable()}</section></>}
 {view==='Audits'&&<section className="panel register">{renderAuditTable()}</section>}
 {view==='Evidence'&&<section className="panel"><div className="panel-heading"><h2>{ws.evidence.length} evidence files</h2></div>{renderEvidenceList({items:ws.evidence})}</section>}
 {view==='Findings'&&<>{findings.map(f=><div key={f.id}>{renderFindingCard({f,a:f.audit})}</div>)}{!findings.length&&<div className="panel empty"><Flag/><h3>No findings yet</h3><p>Open an audit case to record a finding.</p></div>}</>}
 {view==='Reports'&&<div className="reports-grid">{ws.audits.map(a=><section className="panel report-card" key={a.id}><FileText size={27}/><Badge>{['Issued','Closed'].includes(a.status)?'Issued':'Draft'}</Badge><small>{a.reference}{a.sample?' · SAMPLE':''}</small><h2>{a.title}</h2><p>{a.entity}</p><div className="report-info">{a.findings.length} findings · {ws.evidence.filter(e=>e.auditId===a.id).length} evidence files</div><div className="actions"><button onClick={()=>{openAudit(a);setTab('Report')}}>Preview report</button><button aria-label={'Download '+a.reference+' report'} onClick={()=>download(a.reference+'-report.html',report(a),'text/html')}><Download size={17}/></button></div></section>)}{!ws.audits.length&&<div className="panel empty"><FileText/><h3>No reports available</h3><p>Create an audit to begin its report.</p></div>}</div>}
 {view==='Activity'&&<section className="panel"><div className="panel-heading"><h2>Recorded changes</h2><span className="muted">Latest 100 events</span></div><div className="activity-list">{ws.history.map((e,i)=><div key={i}><span className="file-icon"><History size={18}/></span><div><strong>{e.description}</strong><small>{ws.audits.find(a=>a.id===e.auditId)?.reference} · {date(e.created)}</small></div></div>)}{!ws.history.length&&<div className="empty"><History/><h3>No activity yet</h3><p>Your saved changes will be recorded here.</p></div>}</div></section>}
 </>}
 <footer><ShieldCheck size={15}/><span>Audit Workspace · First operational release</span><span>Institutional roles and integrations are planned.</span></footer></main></div>
 <dialog ref={dialog} onCancel={()=>{if(!busy)setModal('')}} onClose={()=>setModal('')}><div className="modal-head"><div className="eyebrow">{modal==='audit'?'NEW ENGAGEMENT':'AUDIT CASE FILE'}</div><button aria-label="Close dialog" disabled={busy} onClick={()=>setModal('')}><X size={20}/></button><h2>{{audit:'Create an audit',finding:'Record a finding',upload:'Upload evidence',response:'Institution response',link:'Link supporting evidence'}[modal]}</h2><p>{modal==='audit'?'Define the engagement before fieldwork begins.':audit?.reference+' · '+audit?.entity}</p></div>{error&&<div className="modal-error" role="alert">{error}</div>}
 <form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const values=Object.fromEntries(data);if(modal==='upload'){data.set('auditId',audit!.id);await action(data,'Evidence uploaded securely')}else await action({...values,action:modal==='audit'?'create':modal==='response'?'respond':modal,auditId:audit?.id,findingId:target?.id},modal==='audit'?'Audit created':'Change saved')}}>
 {modal==='audit'&&<><label>Institution<input name="entity" required maxLength={200} placeholder="Institution or department name"/></label><label>Audit title<input name="title" required maxLength={200} placeholder="e.g. Procurement and expenditure review"/></label><div className="form-grid"><label>Audit type<select name="type"><option>Financial</option><option>Compliance</option><option>Performance</option><option>Internal</option></select></label><label>Audit lead<input name="lead" required maxLength={100} placeholder="Lead auditor’s name"/></label></div><label>Deadline<input name="due" type="date" required/></label><label>Scope<textarea name="scope" rows={4} required maxLength={4000} placeholder="What will this audit examine?"/></label></>}
 {modal==='finding'&&<><label>Finding title<input name="title" required maxLength={200}/></label><div className="form-grid"><label>Risk severity<select name="severity"><option>High</option><option>Critical</option><option>Medium</option><option>Low</option></select></label><label>Action deadline<input name="due" type="date"/></label></div><label>Observation<textarea name="condition" required rows={3} maxLength={4000}/></label><label>Recommendation<textarea name="recommendation" required rows={3} maxLength={4000}/></label><label>Supporting evidence<select name="evidenceId"><option value="">Link evidence later</option>{ws.evidence.filter(e=>e.auditId===audit?.id).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></>}
 {modal==='upload'&&<><div className="upload-zone"><Upload size={29}/><strong>Attach a supporting document</strong><span>PDF, Excel, CSV, Word, text or image · Up to 10 MB</span><input name="file" type="file" required accept=".pdf,.csv,.xlsx,.xls,.docx,.txt,.png,.jpg,.jpeg"/></div><p className="muted">Files are stored privately and fingerprinted at upload. Downloads preserve the original file.</p></>}
 {modal==='response'&&<><p className="selected-finding">{target?.title}</p><label>Institution response<textarea name="response" required rows={5} maxLength={4000} defaultValue={target?.response} placeholder="Record the response and corrective action committed."/></label></>}
 {modal==='link'&&<><p className="selected-finding">{target?.title}</p><label>Supporting evidence<select name="evidenceId" required><option value="">Select an uploaded document</option>{ws.evidence.filter(e=>e.auditId===audit?.id).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><p className="muted">Changing supporting evidence requires the finding to be approved again.</p></>}
 <div className="modal-actions"><button type="button" disabled={busy} onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:<Check size={17}/>} {busy?'Saving…':modal==='audit'?'Create audit':modal==='upload'?'Upload evidence':'Save'}</button></div></form></dialog>
 </div>
}
