import {z} from 'zod';
export type AISource={id:string;name:string;hash:string;text?:string;pdf?:boolean};
export type AICitation={sourceId:string;quote:string;locator:string;quoteMatched:boolean};
export type AIResult={points:{statement:string;citations:AICitation[]}[];gaps:string[];suggestions:{title:string;severity:string;condition:string;recommendation:string;citations:AICitation[]}[]};
export type AIRun={id:string;auditId:string;createdBy:string;created:string;mode:string;model:string;question:string;sources:Omit<AISource,'text'>[];result:AIResult};
const citation=z.object({sourceId:z.string().max(100),quote:z.string().min(1).max(1200),locator:z.string().max(100)});
const schema=z.object({points:z.array(z.object({statement:z.string().max(3000),citations:z.array(citation).max(10)})).max(10),gaps:z.array(z.string().max(1500)).max(10),suggestions:z.array(z.object({title:z.string().max(200),severity:z.enum(['Critical','High','Medium','Low']),condition:z.string().max(4000),recommendation:z.string().max(4000),citations:z.array(citation).max(10)})).max(3)});
const citationJSON={type:'object',additionalProperties:false,properties:{sourceId:{type:'string'},quote:{type:'string'},locator:{type:'string'}},required:['sourceId','quote','locator']};
export const outputSchema={type:'object',additionalProperties:false,properties:{points:{type:'array',items:{type:'object',additionalProperties:false,properties:{statement:{type:'string'},citations:{type:'array',items:citationJSON}},required:['statement','citations']}},gaps:{type:'array',items:{type:'string'}},suggestions:{type:'array',items:{type:'object',additionalProperties:false,properties:{title:{type:'string'},severity:{type:'string',enum:['Critical','High','Medium','Low']},condition:{type:'string'},recommendation:{type:'string'},citations:{type:'array',items:citationJSON}},required:['title','severity','condition','recommendation','citations']}}},required:['points','gaps','suggestions']};
export function validateResult(raw:unknown,sources:AISource[]):AIResult{
 const parsed=schema.parse(raw);let removed=0;
 function citations(input:z.infer<typeof citation>[]):AICitation[]{return input.flatMap<AICitation>(c=>{const source=sources.find(s=>s.id===c.sourceId);if(!source){removed++;return []}if(source.pdf)return [{...c,quoteMatched:false}];const at=source.text?.indexOf(c.quote)??-1;if(at<0){removed++;return []}const line=(source.text!.slice(0,at).match(/\n/g)||[]).length+1;const end=line+(c.quote.match(/\n/g)||[]).length;return [{...c,locator:end===line?'Line '+line:`Lines ${line}–${end}`,quoteMatched:true}]})}
 const points=parsed.points.flatMap(p=>{const refs=citations(p.citations);return refs.length?[{...p,citations:refs}]:[]});const suggestions=parsed.suggestions.flatMap(p=>{const refs=citations(p.citations);return refs.length?[{...p,citations:refs}]:[]});return {points,suggestions,gaps:[...parsed.gaps,...(removed?['Some generated references could not be matched to the selected evidence and were removed.']:[]),...(!points.length&&!suggestions.length?['No supported statements were returned. Review the evidence and narrow the question.']:[])]};
}
