import { env } from 'cloudflare:workers';
export function database() { if (!env.DB) throw new Error('Database unavailable'); return env.DB; }
export function bucket() { if (!env.BUCKET) throw new Error('Evidence storage unavailable'); return env.BUCKET; }
export type FollowUp={officer:string;due:string;action:string;progress:string;status:'Open'|'In progress'|'Awaiting verification'|'Verified';evidenceId:string;submittedBy?:string;submittedAt?:string;verifiedBy?:string;verifiedAt?:string;reviewNote?:string;history?:{at:string;by:string;status:string;note:string}[]};
export type Finding = { id: string; title: string; severity: string; condition: string; recommendation: string; response: string; approved: boolean; evidenceId: string; due: string; preparedBy?:string; approvedBy?:string; approvedAt?:string; sourceFlag?:string; followUp?:FollowUp };
export type Audit = { id: string; reference: string; entity: string; title: string; type: string; lead: string; due: string; scope: string; status: string; sample: boolean; findings: Finding[]; created: string; createdBy?:string; reviewedBy?:string; reviewedAt?:string };
export const statuses = ['Planning', 'Fieldwork', 'Review', 'Issued', 'Closed'];
export function clean(value: unknown, limit = 4000) { return typeof value === 'string' ? value.trim().slice(0, limit) : ''; }
export type Actor={userId:string;name:string;email:string};
export function record(owner:string,auditId:string,description:string,actor:Actor,conditional=false,before:string|null=null,after:string|null=null){return database().prepare('INSERT INTO audit_events (id,owner,audit_id,description,created,actor_id,actor_name,actor_email,before_data,after_data) SELECT ?,?,?,?,?,?,?,?,?,?'+(conditional?' WHERE changes()=1':'')).bind(crypto.randomUUID(),owner,auditId,description,new Date().toISOString(),actor.userId,actor.name,actor.email,before,after);}
export async function storeEvidence(owner:string,auditId:string,id:string,name:string,type:string,hash:string,bytes:ArrayBuffer,actor:Actor,extra:D1PreparedStatement[]=[]){const db=database(),created=new Date().toISOString();await db.batch([db.prepare('INSERT INTO audit_evidence (id,owner,audit_id,name,type,hash,created,uploaded_by_id,uploaded_by_name,uploaded_by_email,upload_status) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,owner,auditId,name,type,hash,created,actor.userId,actor.name,actor.email,'pending'),...extra,record(owner,auditId,`Upload registered: ${name}`,actor)]);try{const stored=await bucket().put(`${owner}/${id}`,bytes,{onlyIf:{etagDoesNotMatch:'*'},httpMetadata:{contentType:type},customMetadata:{actorId:actor.userId,actorName:actor.name,actorEmail:actor.email,auditId,created,sha256:hash}});if(stored===null)throw new Error('Object already exists');await db.batch([db.prepare("UPDATE audit_evidence SET upload_status='available' WHERE id=? AND owner=?").bind(id,owner),record(owner,auditId,`Evidence uploaded: ${name}`,actor)]);}catch(e){await db.batch([db.prepare("UPDATE audit_evidence SET upload_status='unconfirmed' WHERE id=? AND owner=? AND upload_status='pending'").bind(id,owner),record(owner,auditId,`Upload requires storage verification: ${name}`,actor)]);throw e;}}

export async function getAudit(owner: string, id: string): Promise<Audit | null> { const row = await database().prepare('SELECT data FROM audit_cases WHERE id=? AND owner=?').bind(id, owner).first<{data:string}>(); return row ? JSON.parse(row.data) : null; }
export function save(owner: string, a: Audit) { return database().prepare('INSERT INTO audit_cases (id,owner,data,updated) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data, updated=excluded.updated WHERE audit_cases.owner=excluded.owner').bind(a.id,owner,JSON.stringify(a),new Date().toISOString()); }
export function samples(): Audit[] { return [
{ id: crypto.randomUUID(),reference:'DEMO-001',entity:'Demonstration District Council',title:'Procurement & expenditure review',type:'Compliance',lead:'A. Kamara',due:'2026-10-20',scope:'Review procurement documentation, expenditure authorisation and reconciliation for the sample reporting period.',status:'Fieldwork',sample:true,findings:[{id:crypto.randomUUID(),title:'Supporting procurement documents outstanding',severity:'High',condition:'The demonstration file contains three transactions awaiting supporting documentation. This is fictional training data.',recommendation:'Obtain the procurement file and reconcile each payment to the approved contract.',response:'',approved:false,evidenceId:'',due:'2026-10-15'}],created:new Date().toISOString()},
{ id:crypto.randomUUID(),reference:'DEMO-002',entity:'Demonstration Health Directorate',title:'Medical supplies inventory',type:'Performance',lead:'M. Sesay',due:'2026-11-05',scope:'Assess inventory records, stock counts and distribution controls using fictional training records.',status:'Planning',sample:true,findings:[],created:new Date().toISOString()},
{ id:crypto.randomUUID(),reference:'DEMO-003',entity:'Demonstration Education Office',title:'Payroll controls assessment',type:'Financial',lead:'F. Conteh',due:'2026-10-28',scope:'Review payroll approval, staff records and reconciliation of the sample payroll.',status:'Review',sample:true,findings:[],created:new Date().toISOString()}
]; }
