import { env } from 'cloudflare:workers';
export function database() { if (!env.DB) throw new Error('Database unavailable'); return env.DB; }
export function bucket() { if (!env.BUCKET) throw new Error('Evidence storage unavailable'); return env.BUCKET; }
export type Finding = { id: string; title: string; severity: string; condition: string; recommendation: string; response: string; approved: boolean; evidenceId: string; due: string; preparedBy?:string; approvedBy?:string; approvedAt?:string; sourceFlag?:string };
export type Audit = { id: string; reference: string; entity: string; title: string; type: string; lead: string; due: string; scope: string; status: string; sample: boolean; findings: Finding[]; created: string; createdBy?:string; reviewedBy?:string; reviewedAt?:string };
export const statuses = ['Planning', 'Fieldwork', 'Review', 'Issued', 'Closed'];
export function clean(value: unknown, limit = 4000) { return typeof value === 'string' ? value.trim().slice(0, limit) : ''; }
export function record(owner: string, auditId: string, description: string) { return database().prepare('INSERT INTO audit_events (id,owner,audit_id,description,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),owner,auditId,description,new Date().toISOString()); }
export async function getAudit(owner: string, id: string): Promise<Audit | null> { const row = await database().prepare('SELECT data FROM audit_cases WHERE id=? AND owner=?').bind(id, owner).first<{data:string}>(); return row ? JSON.parse(row.data) : null; }
export function save(owner: string, a: Audit) { return database().prepare('INSERT INTO audit_cases (id,owner,data,updated) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data, updated=excluded.updated WHERE audit_cases.owner=excluded.owner').bind(a.id,owner,JSON.stringify(a),new Date().toISOString()); }
export function samples(): Audit[] { return [
{ id: crypto.randomUUID(),reference:'DEMO-001',entity:'Demonstration District Council',title:'Procurement & expenditure review',type:'Compliance',lead:'A. Kamara',due:'2026-10-20',scope:'Review procurement documentation, expenditure authorisation and reconciliation for the sample reporting period.',status:'Fieldwork',sample:true,findings:[{id:crypto.randomUUID(),title:'Supporting procurement documents outstanding',severity:'High',condition:'The demonstration file contains three transactions awaiting supporting documentation. This is fictional training data.',recommendation:'Obtain the procurement file and reconcile each payment to the approved contract.',response:'',approved:false,evidenceId:'',due:'2026-10-15'}],created:new Date().toISOString()},
{ id:crypto.randomUUID(),reference:'DEMO-002',entity:'Demonstration Health Directorate',title:'Medical supplies inventory',type:'Performance',lead:'M. Sesay',due:'2026-11-05',scope:'Assess inventory records, stock counts and distribution controls using fictional training records.',status:'Planning',sample:true,findings:[],created:new Date().toISOString()},
{ id:crypto.randomUUID(),reference:'DEMO-003',entity:'Demonstration Education Office',title:'Payroll controls assessment',type:'Financial',lead:'F. Conteh',due:'2026-10-28',scope:'Review payroll approval, staff records and reconciliation of the sample payroll.',status:'Review',sample:true,findings:[],created:new Date().toISOString()}
]; }
