import {database,record,type Actor,type Audit} from './audit';
export const deadlinePolicy={reminderDays:3,reviewerDays:7,ownerDays:14,timeZone:'Africa/Freetown'};
export type DeadlineAlert={id:string;auditId:string;findingId:string;kind:string;level:string;due:string;title:string;responsible:string;recipients:string[];daysOverdue:number;created:string;state:'open'|'acknowledged'|'resolved';stateAt:string};
type Candidate=Omit<DeadlineAlert,'id'|'created'|'state'|'stateAt'>;
type Team={email:string;name:string;role:string;active:string};
const DAY=86400000;
export function deadlineCandidates(a:Audit,today:string,ownerEmail:string,team:Team[]):Candidate[]{
 if(a.status==='Closed'||a.sample)return [];
 const reviewers=team.filter(m=>m.active==='yes'&&m.role==='Reviewer').map(m=>m.email),escalation=[...new Set([ownerEmail,...reviewers])];
 const result:Candidate[]=[];
 function add(findingId:string,due:string,title:string,responsible:string,kind:string,review=false){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(due))return;
  const when=Date.parse(due+'T00:00:00Z');if(!Number.isFinite(when)||new Date(when).toISOString().slice(0,10)!==due)return;
  const days=Math.round((Date.parse(today+'T00:00:00Z')-when)/DAY);if(days < -deadlinePolicy.reminderDays)return;
  const level=days>=deadlinePolicy.ownerDays?'Owner escalation':days>=deadlinePolicy.reviewerDays?'Reviewer escalation':days>0?'Overdue':days===0?'Due today':'Due soon';
  const assigned=team.filter(m=>m.active==='yes'&&(m.email.toLowerCase()===responsible.toLowerCase()||m.name.toLowerCase()===responsible.toLowerCase()));
  const recipients=level==='Owner escalation'?[ownerEmail]:level==='Reviewer escalation'||review?escalation:[...new Set([ownerEmail,...assigned.map(m=>m.email)])];
  result.push({auditId:a.id,findingId,kind:review?'Independent verification':kind,level,due,title,responsible:review?'Independent reviewer':responsible||'Unassigned',daysOverdue:Math.max(0,days),recipients:recipients.sort()});
 }
 if(a.status!=='Issued')add('',a.due,a.title,a.lead,'Audit deadline');
 for(const f of a.findings){if(f.followUp?.status==='Verified')continue;const follow=f.followUp;add(f.id,follow?.due||f.due,f.title,follow?.officer||'', 'Corrective action',follow?.status==='Awaiting verification');}
 return result;
}
export async function readAlerts(owner:string){const rows=await database().prepare(`SELECT a.id,a.audit_id AS auditId,a.finding_id AS findingId,a.kind,a.level,a.due,a.title,a.responsible,a.recipients,a.created,t.state,t.created AS stateAt FROM audit_alerts a JOIN audit_alert_transitions t ON t.seq=(SELECT MAX(seq) FROM audit_alert_transitions WHERE alert_id=a.id AND owner=a.owner) WHERE a.owner=? ORDER BY CASE t.state WHEN 'open' THEN 0 WHEN 'acknowledged' THEN 1 ELSE 2 END,a.created DESC LIMIT 201`).bind(owner).all<Omit<DeadlineAlert,'recipients'|'daysOverdue'> & {recipients:string}>();const today=new Date().toISOString().slice(0,10);return rows.results.slice(0,200).map(r=>({...r,recipients:JSON.parse(r.recipients) as string[],daysOverdue:Math.max(0,Math.round((Date.parse(today+'T00:00:00Z')-Date.parse(r.due+'T00:00:00Z'))/DAY))}));}
export async function alertCounts(owner:string){return await database().prepare(`SELECT SUM(CASE WHEN t.state IN ('open','acknowledged') THEN 1 ELSE 0 END) AS active,SUM(CASE WHEN t.state IN ('open','acknowledged') AND a.level IN ('Reviewer escalation','Owner escalation') THEN 1 ELSE 0 END) AS escalated FROM audit_alerts a JOIN audit_alert_transitions t ON t.seq=(SELECT MAX(seq) FROM audit_alert_transitions WHERE alert_id=a.id AND owner=a.owner) WHERE a.owner=?`).bind(owner).first<{active:number|null;escalated:number|null}>();}
const systemActor:Actor={userId:'system:deadline-monitor',name:'Automated deadline monitor',email:'system'};
export async function runDeadlineMonitor(owner:string,initiatedBy:Actor=systemActor,saveRun=true,now=new Date()){
 const db=database(),created=now.toISOString(),today=created.slice(0,10);
 const workspace=await db.prepare('SELECT email FROM audit_workspace WHERE id=? AND owner=?').bind('main',owner).first<{email:string}>();if(!workspace)throw new Error('Workspace not initialised');
 const audits=await db.prepare('SELECT id,data FROM audit_cases WHERE owner=?').bind(owner).all<{id:string;data:string}>();const team=await db.prepare('SELECT email,name,role,active FROM audit_members').all<Team>();
 const current=await db.prepare(`SELECT a.id,a.audit_id AS auditId,a.title,t.state FROM audit_alerts a JOIN audit_alert_transitions t ON t.seq=(SELECT MAX(seq) FROM audit_alert_transitions WHERE alert_id=a.id AND owner=a.owner) WHERE a.owner=? AND t.state!='resolved'`).bind(owner).all<{id:string;auditId:string;title:string;state:string}>();
 const desired=new Set<string>(),original=new Map(audits.results.map(a=>[a.id,a.data]));let opened=0,resolved=0,escalationsOpened=0;
 for(const row of audits.results){const a=JSON.parse(row.data) as Audit;for(const candidate of deadlineCandidates(a,today,workspace.email,team.results)){
  const identity=JSON.stringify([owner,candidate.auditId,candidate.findingId,candidate.kind,candidate.level,candidate.due,candidate.responsible,candidate.recipients,candidate.title]);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(identity));const id=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');desired.add(id);
  const result=await db.batch([db.prepare(`INSERT INTO audit_alerts(id,owner,audit_id,finding_id,kind,level,due,title,responsible,recipients,created) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM audit_cases WHERE id=? AND owner=? AND data=?) AND NOT EXISTS(SELECT 1 FROM audit_alerts WHERE id=?)`).bind(id,owner,a.id,candidate.findingId,candidate.kind,candidate.level,candidate.due,candidate.title,candidate.responsible,JSON.stringify(candidate.recipients),created,a.id,owner,row.data,id),db.prepare(`INSERT INTO audit_alert_transitions(owner,alert_id,state,created,actor_id,actor_name,actor_email) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM audit_cases WHERE id=? AND owner=? AND data=?) AND EXISTS(SELECT 1 FROM audit_alerts WHERE id=? AND owner=?) AND COALESCE((SELECT state FROM audit_alert_transitions WHERE alert_id=? AND owner=? ORDER BY seq DESC LIMIT 1),'resolved')='resolved'`).bind(owner,id,'open',created,systemActor.userId,systemActor.name,systemActor.email,a.id,owner,row.data,id,owner,id,owner),record(owner,a.id,`${candidate.level}: ${candidate.title}; due ${candidate.due}; responsible ${candidate.responsible}; in-app recipients ${candidate.recipients.join(', ')}`,systemActor,true)]);opened+=result[1].meta.changes;if(candidate.level.includes('escalation'))escalationsOpened+=result[1].meta.changes;
 }}
 for(const alert of current.results){if(desired.has(alert.id))continue;const snapshot=original.get(alert.auditId);if(!snapshot)continue;const result=await db.batch([db.prepare(`INSERT INTO audit_alert_transitions(owner,alert_id,state,created,actor_id,actor_name,actor_email) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM audit_cases WHERE id=? AND owner=? AND data=?) AND (SELECT state FROM audit_alert_transitions WHERE alert_id=? AND owner=? ORDER BY seq DESC LIMIT 1) IN ('open','acknowledged')`).bind(owner,alert.id,'resolved',created,systemActor.userId,systemActor.name,systemActor.email,alert.auditId,owner,snapshot,alert.id,owner),record(owner,alert.auditId,`Deadline alert resolved or superseded: ${alert.title}`,systemActor,true)]);resolved+=result[0].meta.changes;}
 const counts=await alertCounts(owner);const summary={opened,resolved,escalationsOpened,active:counts?.active||0,escalated:counts?.escalated||0,checkedAt:created};
 if(saveRun)await db.batch([db.prepare('INSERT INTO audit_monitor_runs(id,owner,created,actor_id,actor_name,actor_email,data) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,created,initiatedBy.userId,initiatedBy.name,initiatedBy.email,JSON.stringify(summary)),record(owner,'workspace',`Deadline check completed: ${opened} new alerts, ${resolved} resolved; ${summary.active} active`,initiatedBy)]);
 return summary;
}
export async function acknowledgeAlert(owner:string,id:string,actor:Actor){const db=database();const alert=await db.prepare('SELECT audit_id,title FROM audit_alerts WHERE id=? AND owner=?').bind(id,owner).first<{audit_id:string;title:string}>();if(!alert)return false;const result=await db.batch([db.prepare(`INSERT INTO audit_alert_transitions(owner,alert_id,state,created,actor_id,actor_name,actor_email) SELECT ?,?,?,?,?,?,? WHERE (SELECT state FROM audit_alert_transitions WHERE alert_id=? AND owner=? ORDER BY seq DESC LIMIT 1)='open'`).bind(owner,id,'acknowledged',new Date().toISOString(),actor.userId,actor.name,actor.email,id,owner),record(owner,alert.audit_id,`Deadline alert acknowledged: ${alert.title}`,actor,true)]);return !!result[0].meta.changes;}
