import {env} from 'cloudflare:workers';
import {database,bucket,record,type Actor} from './audit';
export const cleanEvidenceSQL=`EXISTS(SELECT 1 FROM audit_file_scans s WHERE s.owner=audit_evidence.owner AND s.file_id=audit_evidence.id AND s.hash=audit_evidence.hash AND s.seq=(SELECT MAX(seq) FROM audit_file_scans WHERE owner=s.owner AND file_id=s.file_id) AND s.verdict='clean' AND s.created>=strftime('%Y-%m-%dT%H:%M:%fZ','now','-7 days'))`;
export const scanVerdictSQL=`CASE WHEN ${cleanEvidenceSQL} THEN 'clean' WHEN (SELECT verdict FROM audit_file_scans WHERE owner=audit_evidence.owner AND file_id=audit_evidence.id ORDER BY seq DESC LIMIT 1)='clean' THEN 'expired or mismatched' ELSE COALESCE((SELECT verdict FROM audit_file_scans WHERE owner=audit_evidence.owner AND file_id=audit_evidence.id ORDER BY seq DESC LIMIT 1),'unscanned') END`;
export async function evidenceIsClean(owner:string,id:string){return !!await database().prepare(`SELECT id FROM audit_evidence WHERE owner=? AND id=? AND upload_status='available' AND ${cleanEvidenceSQL}`).bind(owner,id).first();}
export async function scanEvidence(owner:string,id:string,actor:Actor){
 if(!env.AUDIT_SCANNER_URL||!env.AUDIT_SCANNER_TOKEN)return {verdict:'unscanned',reason:'Scanner connection is not configured'};
 const endpoint=new URL(env.AUDIT_SCANNER_URL);if(endpoint.protocol!=='https:'||endpoint.username||endpoint.password||endpoint.hash)throw new Error('Invalid scanner configuration');
 const file=await database().prepare("SELECT name,hash,audit_id FROM audit_evidence WHERE owner=? AND id=? AND upload_status='available'").bind(owner,id).first<{name:string;hash:string;audit_id:string}>();if(!file)throw new Error('Stored evidence not found');
 let verdict='error',engine='Unavailable',version='Unknown',signatures='Unknown';
 try{const object=await bucket().get(`${owner}/${id}`);if(!object)throw new Error('Missing object');const bytes=await object.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');if(digest!==file.hash)throw new Error('Integrity mismatch');
 const response=await fetch(endpoint,{method:'POST',redirect:'error',signal:AbortSignal.timeout(45000),headers:{Authorization:`Bearer ${env.AUDIT_SCANNER_TOKEN}`,'Content-Type':'application/octet-stream','X-Evidence-SHA256':file.hash},body:bytes});const reader=response.body?.getReader();let text='',size=0;if(!reader)throw new Error('Missing scan result');for(;;){const chunk=await reader.read();if(chunk.done)break;size+=chunk.value.byteLength;if(size>16000){await reader.cancel();throw new Error('Scan result too large')}text+=new TextDecoder().decode(chunk.value,{stream:true});}if(!response.ok)throw new Error('Scanner failed');const result=JSON.parse(text);if(!['clean','infected'].includes(result.verdict)||result.sha256!==file.hash||typeof result.engine!=='string'||typeof result.version!=='string'||typeof result.signaturesUpdatedAt!=='string')throw new Error('Invalid scanner result');const age=Date.now()-Date.parse(result.signaturesUpdatedAt);if(!Number.isFinite(age)||age< -86400000||age>7*86400000)throw new Error('Stale scanner signatures');verdict=result.verdict;engine=result.engine.slice(0,100);version=result.version.slice(0,100);signatures=result.signaturesUpdatedAt;
 }catch{/* Failed, mismatched or stale scans never release a file. */}
 await database().batch([database().prepare('INSERT INTO audit_file_scans(owner,file_id,hash,verdict,engine,version,signatures,created,actor_id,actor_name,actor_email) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(owner,id,file.hash,verdict,engine,version,signatures,new Date().toISOString(),actor.userId,actor.name,actor.email),record(owner,file.audit_id,`Evidence malware scan ${verdict}: ${file.name}`,actor)]);return {verdict};
}
