export type Transaction={row:number;date:string;reference:string;payee:string;amount:number|null;invoice:string;approval:string};
export type Exception={id:string;rule:string;severity:string;rows:number[];detail:string};
export type CheckResult={id:string;auditId:string;evidenceId:string;name:string;created:string;createdBy:string;rules:{largeAmount:number;medianFactor:number};transactions:Transaction[];exceptions:Exception[];summary:{rows:number;total:number;flaggedRows:number;currency:string;median:number}};
export function parseCSV(input:string):string[][]{
 const rows:string[][]=[];let row:string[]=[],cell='',quoted=false,closed=false;
 input=input.replace(/^\uFEFF/,'');
 for(let i=0;i<input.length;i++){const c=input[i];if(quoted){if(c==='"'){if(input[i+1]==='"'){cell+='"';i++}else{quoted=false;closed=true}}else cell+=c;continue}
 if(c==='"'){if(cell||closed)throw new Error('Invalid CSV quoting. Export a standard comma-separated CSV.');quoted=true}
 else if(c===','){row.push(cell);cell='';closed=false}
 else if(c==='\n'||c==='\r'){if(c==='\r'&&input[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';closed=false}
 else{if(closed&&!/\s/.test(c))throw new Error('Unexpected text after a quoted CSV field.');if(!closed)cell+=c}
 }
 if(quoted)throw new Error('The CSV has an unclosed quoted field.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;
}
const normal=(s:string)=>s.trim().toLowerCase().replace(/\s+/g,' ');
export function analyseCSV(text:string,largeAmount=100000,medianFactor=5){
 const csv=parseCSV(text);if(csv.length<2)throw new Error('The CSV needs a header and at least one transaction.');if(csv.length>2001)throw new Error('Import at most 2,000 transactions per file.');
 const headers=csv[0].map(normal);const required=['date','reference','payee','amount','invoice','approval'];for(const h of required)if(!headers.includes(h))throw new Error(`Missing ${h} column. Download the CSV template for the required format.`);if(new Set(headers).size!==headers.length)throw new Error('Duplicate column names are not supported.');
 const transactions:Transaction[]=csv.slice(1).map((cells,i)=>{if(cells.length!==headers.length)throw new Error(`Transaction ${i+1} has a different number of columns from the header.`);if(cells.some(c=>c.length>200))throw new Error(`Transaction ${i+1} contains a field longer than 200 characters.`);const field=(name:string)=>cells[headers.indexOf(name)]?.trim()||'';if(headers.includes('currency')&&field('currency').toUpperCase()!=='SLE')throw new Error('This check supports SLE only. Import other currencies separately after conversion.');const raw=field('amount');const value=/^-?\d+(\.\d{1,2})?$/.test(raw)?Number(raw):NaN;return {row:i+1,date:field('date').slice(0,100),reference:field('reference').slice(0,200),payee:field('payee').slice(0,200),amount:Number.isFinite(value)&&Math.abs(value)<=1e12?value:null,invoice:field('invoice').slice(0,200),approval:field('approval').slice(0,200)}});
 const exceptions:Exception[]=[];const flag=(rule:string,severity:string,rows:number[],detail:string)=>exceptions.push({id:String(exceptions.length+1),rule,severity,rows,detail});
 for(const t of transactions){const missing=['date','reference','payee','invoice','approval'].filter(k=>!t[k as keyof Transaction]);if(missing.length)flag('Missing records','Medium',[t.row],`Missing ${missing.join(', ')}.`);if(t.amount===null||t.amount<=0)flag('Invalid amount','High',[t.row],'Amount must be a positive number, with at most two decimal places and no currency symbols or thousands separators.');if(t.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(t.date)||!Number.isFinite(Date.parse(t.date))||new Date(t.date).toISOString().slice(0,10)!==t.date))flag('Invalid date','Medium',[t.row],'Date must be a valid YYYY-MM-DD date.');}
 const refs=new Map<string,number[]>(),similar=new Map<string,number[]>();for(const t of transactions){if(t.reference){const k=normal(t.reference);refs.set(k,[...(refs.get(k)||[]),t.row])}if(t.date&&t.payee&&t.amount!==null){const k=JSON.stringify([t.date,normal(t.payee),t.amount]);similar.set(k,[...(similar.get(k)||[]),t.row])}}
 for(const rows of refs.values())if(rows.length>1)flag('Duplicate reference','High',rows,'The same payment reference appears more than once. Verify whether the entries represent a repeated payment or a legitimate split.');for(const rows of similar.values())if(rows.length>1)flag('Possible repeated payment','High',rows,'Same payee, amount and date. Check the supporting documents before drawing a conclusion.');
 const amounts=transactions.flatMap(t=>t.amount!==null&&t.amount>0?[t.amount]:[]).sort((a,b)=>a-b);const median=amounts.length?(amounts.length%2?amounts[(amounts.length-1)/2]:(amounts[amounts.length/2-1]+amounts[amounts.length/2])/2):0;
 for(const t of transactions)if(t.amount!==null&&t.amount>0){if(t.amount>largeAmount)flag('Large amount','Medium',[t.row],`Amount exceeds the configured SLE ${largeAmount.toLocaleString('en-GB')} threshold.`);if(amounts.length>=5&&median>0&&t.amount>median*medianFactor)flag('Amount outlier','Medium',[t.row],`Amount exceeds ${medianFactor} times this file’s median of SLE ${median.toLocaleString('en-GB')}.`)}
 const cents=amounts.reduce((s,n)=>s+Math.round(n*100),0);if(!Number.isSafeInteger(cents))throw new Error('The file total exceeds the supported precision. Split the dataset into smaller files.');return {transactions,exceptions,summary:{rows:transactions.length,total:cents/100,flaggedRows:new Set(exceptions.flatMap(e=>e.rows)).size,currency:'SLE',median},rules:{largeAmount,medianFactor}};
}
