import {config} from './config.js';
const $=id=>document.getElementById(id);
let session=null,cases=[],caseCursor=null,activityCursor=null;
const notice=text=>{$('notice').textContent=text};
function element(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
async function request(path,body,auth=true){
 if(auth&&(!session||Date.now()>=session.expiresAt))throw Error('Your session expired. Sign in again.');
 const response=await fetch(config.url+path,{method:'POST',redirect:'error',headers:{apikey:config.publishableKey,'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+session.accessToken}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});
 const value=await response.json();if(!response.ok){if(value.code==='40001')throw Error('This case changed. Refresh it before saving again.');throw Error(auth?'The operation was denied or could not complete. Check your audit membership and inputs.':'Sign-in failed. Check your verified email and password.');}return value;
}
const rpc=(name,body)=>request('/rest/v1/rpc/audit_test_'+name,body);
async function busy(job){document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await job()}catch(e){notice(e.message)}finally{document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
function resetCase(){$('case-form').reset();$('case-heading').textContent='Create a test audit'}
function drawCases(){
 $('cases').replaceChildren();const select=$('upload-form').elements.case;select.replaceChildren(element('option','Select a saved audit'));select.firstChild.value='';
 for(const c of cases){const row=element('article','');row.className='case';row.append(element('strong',c.title),element('p',`${c.entity} · ${c.status} · revision ${c.version}`));const edit=element('button','Edit case');edit.className='secondary';edit.onclick=()=>{const f=$('case-form');for(const key of ['id','version','entity','title','audit_type','lead','scope','due','status'])f.elements[key].value=c[key];$('case-heading').textContent='Edit saved audit';f.scrollIntoView({behavior:'smooth'})};row.append(edit);$('cases').append(row);const option=element('option',c.title);option.value=c.id;select.append(option)}
 if(!cases.length)$('cases').append(element('p','No test audits saved yet.'));
}
async function loadCases(append=false){const body={p_workspace:config.workspace,p_limit:50};if(append&&caseCursor){body.p_before=caseCursor.updated_at;body.p_before_id=caseCursor.id}const page=await rpc('list_cases',body);cases=append?[...cases,...page]:page;caseCursor=page.at(-1)||null;$('more-cases').hidden=page.length<50;drawCases()}
async function loadActivity(append=false){const body={p_workspace:config.workspace,p_limit:100};if(append&&activityCursor)body.p_before=activityCursor;const page=await rpc('activity',body);if(!append)$('activity').replaceChildren();for(const a of page){const row=element('article','');row.className='event';row.append(element('strong',a.action),element('small',`${a.actor_name} · ${a.actor_email} · ${a.created_at} · account ${a.actor_id}`));if(a.before_data||a.after_data){const details=element('details','');details.append(element('summary','View preserved revision'),element('pre',JSON.stringify({before:a.before_data,after:a.after_data},null,2)));row.append(details)}$('activity').append(row)}activityCursor=page.at(-1)?.seq||null;$('more-activity').hidden=page.length<100}
$('login-form').onsubmit=e=>{e.preventDefault();void busy(async()=>{const f=e.currentTarget;const email=f.elements.email.value.trim();const password=f.elements.password.value;let auth;try{auth=await request('/auth/v1/token?grant_type=password',{email,password},false)}finally{f.elements.password.value=''}session={accessToken:auth.access_token,expiresAt:Date.now()+auth.expires_in*1000};try{await rpc('activate_owner',{p_workspace:config.workspace,p_display_name:'Henry Moseray'});await loadCases();await loadActivity();$('identity').textContent='Audit test workspace · '+email;$('login').hidden=true;$('workspace').hidden=false;notice('Connected to the live Supabase test backend. Use fictional data only.')}catch(error){session=null;throw error}})};
$('case-form').onsubmit=e=>{e.preventDefault();void busy(async()=>{const f=e.currentTarget,p=Object.fromEntries(new FormData(f));const args={p_entity:p.entity,p_title:p.title,p_type:p.audit_type,p_lead:p.lead,p_scope:p.scope,p_due:p.due};if(p.id)await rpc('update_case',{...args,p_id:p.id,p_version:Number(p.version),p_status:p.status});else await rpc('create_case',{...args,p_workspace:config.workspace});resetCase();await loadCases();await loadActivity();notice('Audit saved with its actor and preserved revision.')})};
$('upload-form').onsubmit=e=>{e.preventDefault();void busy(async()=>{const f=e.currentTarget,file=f.elements.file.files[0];if(!file||file.size<1||file.size>10*1024*1024)throw Error('Choose a file between 1 byte and 10 MB.');if(!/\.(pdf|csv|txt|xlsx|xls|docx|png|jpg|jpeg)$/i.test(file.name))throw Error('Choose a supported document, text or image file.');const bytes=await file.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');const registered=await rpc('register_evidence',{p_case:f.elements.case.value,p_filename:file.name,p_sha256:hash,p_size:file.size,p_type:file.type||'application/octet-stream'});const response=await fetch(`${config.url}/storage/v1/object/${registered.bucket}/${registered.object_key}`,{method:'POST',redirect:'error',headers:{apikey:config.publishableKey,Authorization:'Bearer '+session.accessToken,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:bytes,signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('The file registration was preserved, but storage upload failed. Its history remains available.');await rpc('confirm_upload',{p_evidence:registered.id});await loadActivity();f.reset();notice('Test evidence uploaded. It remains quarantined until a verified malware scan is available.')})};
$('logout').onclick=()=>void busy(async()=>{if(session){try{await fetch(config.url+'/auth/v1/logout',{method:'POST',headers:{apikey:config.publishableKey,Authorization:'Bearer '+session.accessToken},redirect:'error',signal:AbortSignal.timeout(10000)})}finally{session=null}}cases=[];caseCursor=activityCursor=null;$('cases').replaceChildren();$('activity').replaceChildren();resetCase();$('workspace').hidden=true;$('login').hidden=false;notice('Signed out. No credentials or audit data are stored in browser storage.')});
$('new-case').onclick=resetCase;$('refresh').onclick=()=>void busy(async()=>{await loadCases();await loadActivity();notice('Saved records refreshed.')});$('more-cases').onclick=()=>void busy(()=>loadCases(true));$('more-activity').onclick=()=>void busy(()=>loadActivity(true));
