import { sqliteTable, text, integer, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const cases = sqliteTable('audit_cases', { id: text('id').primaryKey(), owner: text('owner').notNull(), data: text('data').notNull(), updated: text('updated').notNull() });
export const versions=sqliteTable('audit_versions',{id:text('id').primaryKey(),owner:text('owner').notNull(),auditId:text('audit_id').notNull(),data:text('data').notNull(),created:text('created').notNull()});
export const files = sqliteTable('audit_evidence', { id: text('id').primaryKey(), owner: text('owner').notNull(), auditId: text('audit_id').notNull(), name: text('name').notNull(), type: text('type').notNull(), hash: text('hash').notNull(), uploadedById:text('uploaded_by_id'),uploadedByName:text('uploaded_by_name'),uploadedByEmail:text('uploaded_by_email'),uploadStatus:text('upload_status').notNull().default('available'), created: text('created').notNull() });
export const events = sqliteTable('audit_events', { id: text('id').primaryKey(), owner: text('owner').notNull(), auditId: text('audit_id').notNull(), description: text('description').notNull(),actorId:text('actor_id'),actorName:text('actor_name'),actorEmail:text('actor_email'),beforeData:text('before_data'),afterData:text('after_data'), created: text('created').notNull() });
export const workspace = sqliteTable('audit_workspace', { id:text('id').primaryKey(), owner:text('owner').notNull(), email:text('email').notNull() });
export const members = sqliteTable('audit_members', { email:text('email').primaryKey(), name:text('name').notNull(), role:text('role').notNull(), active:text('active').notNull(), userId:text('user_id'), created:text('created').notNull() },table=>[uniqueIndex('audit_members_user_id_unique').on(table.userId)]);
export const checks = sqliteTable('audit_checks', { id:text('id').primaryKey(), owner:text('owner').notNull(), auditId:text('audit_id').notNull(), data:text('data').notNull(), created:text('created').notNull() });
export const aiRuns = sqliteTable('audit_ai_runs', {id:text('id').primaryKey(),owner:text('owner').notNull(),auditId:text('audit_id').notNull(),createdBy:text('created_by').notNull(),created:text('created').notNull(),mode:text('mode').notNull(),model:text('model').notNull(),status:text('status').notNull(),data:text('data').notNull()});

export const alerts=sqliteTable('audit_alerts',{id:text('id').primaryKey(),owner:text('owner').notNull(),auditId:text('audit_id').notNull(),findingId:text('finding_id').notNull(),kind:text('kind').notNull(),level:text('level').notNull(),due:text('due').notNull(),title:text('title').notNull(),responsible:text('responsible').notNull(),recipients:text('recipients').notNull(),created:text('created').notNull()});
export const alertTransitions=sqliteTable('audit_alert_transitions',{seq:integer('seq').primaryKey({autoIncrement:true}),owner:text('owner').notNull(),alertId:text('alert_id').notNull(),state:text('state').notNull(),created:text('created').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),actorEmail:text('actor_email').notNull()});
export const monitorRuns=sqliteTable('audit_monitor_runs',{id:text('id').primaryKey(),owner:text('owner').notNull(),created:text('created').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),actorEmail:text('actor_email').notNull(),data:text('data').notNull()});
