import { z } from 'zod';
import { getChatGPTUser } from '../../chatgpt-auth';
import { database, bucket, clean, getAudit, record, save, samples, statuses, type Audit } from '../../../lib/audit';
export async function GET() { const user=await getChatGPTUser(); if(!user) return Response.json({error:'Sign in to access your audit workspace.'},{status:401}); try { const db=database(); const audits=await db.prepare('SELECT data FROM audit_cases WHERE owner=? ORDER BY updated DESC').bind(user.userId).all<{data:string}>(); const evidence=await db.prepare('SELECT id,audit_id AS auditId,name,type,hash,created FROM audit_evidence WHERE owner=? ORDER BY created DESC').bind(user.userId).all(); const history=await db.prepare('SELECT audit_id AS auditId,description,created FROM audit_events WHERE owner=? ORDER BY created DESC LIMIT 100').bind(user.userId).all(); return Response.json({user:user.displayName,audits:audits.results.map(r=>JSON.parse(r.data)),evidence:evidence.results,history:history.results}); } catch(e) { console.error(e); return Response.json({error:'Your workspace could not be loaded. Please retry.'},{status:503}); } }
export async function POST(req:Request) { const user=await getChatGPTUser(); if(!user) return Response.json({error:'Sign in to save changes.'},{status:401}); const origin=req.headers.get('origin'); if(origin && origin!==new URL(req.url).origin) return Response.json({error:'Invalid request origin.'},{status:403}); try {
 const owner=user.userId; const db=database();
 if(req.headers.get('content-type')?.includes('multipart/form-data')) { const form=await req.formData(); const id=clean(form.get('auditId'),100); const audit=await getAudit(owner,id); if(!audit) return Response.json({error:'Audit not found.'},{status:404}); if(['Issued','Closed'].includes(audit.status)) return Response.json({error:'Evidence is locked after report issue.'},{status:409}); const file=form.get('file'); if(!(file instanceof File) || !file.size || file.size>10*1024*1024) return Response.json({error:'Choose a file between 1 byte and 10 MB.'},{status:400}); const allowed=['pdf','csv','xlsx','xls','docx','txt','png','jpg','jpeg']; const name=clean(file.name,200); if(!allowed.includes(name.split('.').pop()?.toLowerCase()||'')) return Response.json({error:'Use PDF, spreadsheet, document, text or image files.'},{status:400}); const bytes=await file.arrayBuffer(); const digest=await crypto.subtle.digest('SHA-256',bytes); const hash=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join(''); const fileId=crypto.randomUUID(); await bucket().put(`${owner}/${fileId}`,bytes,{httpMetadata:{contentType:'application/octet-stream'}}); try { await db.batch([db.prepare('INSERT INTO audit_evidence (id,owner,audit_id,name,type,hash,created) VALUES (?,?,?,?,?,?,?)').bind(fileId,owner,id,name,file.type||'application/octet-stream',hash,new Date().toISOString()),record(owner,id,`Evidence uploaded: ${name}`)]); } catch(e) { await bucket().delete(`${owner}/${fileId}`); throw e; } return Response.json({ok:true}); }
 const result=z.object({action:z.string(),auditId:z.string().optional(),entity:z.string().optional(),title:z.string().optional(),lead:z.string().optional(),due:z.string().optional(),scope:z.string().optional(),type:z.string().optional(),status:z.string().optional(),severity:z.string().optional(),condition:z.string().optional(),recommendation:z.string().optional(),evidenceId:z.string().optional(),findingId:z.string().optional(),response:z.string().optional()}).safeParse(await req.json()); if(!result.success)return Response.json({error:'Invalid request fields.'},{status:400});const p=result.data;
 if(p.action==='samples') { const count=await db.prepare('SELECT COUNT(*) AS n FROM audit_cases WHERE owner=?').bind(owner).first<{n:number}>(); if(count?.n) return Response.json({error:'Sample audits can only be loaded into an empty workspace.'},{status:409}); const all=samples(); await db.batch(all.flatMap(a=>[save(owner,a),record(owner,a.id,'Demonstration audit created')])); return Response.json({ok:true}); }
 if(p.action==='create') { const entity=clean(p.entity,200),title=clean(p.title,200),lead=clean(p.lead,100),due=clean(p.due,10),scope=clean(p.scope); if(!entity||!title||!lead||!scope||!/^\d{4}-\d{2}-\d{2}$/.test(due)||!['Financial','Compliance','Performance','Internal'].includes(p.type||'')) return Response.json({error:'Complete the institution, title, type, lead, deadline and scope.'},{status:400}); const id=crypto.randomUUID(); const a:Audit={id,reference:`AUD-${new Date().getFullYear()}-${id.slice(0,6).toUpperCase()}`,entity,title,type:p.type!,lead,due,scope,status:'Planning',sample:false,findings:[],created:new Date().toISOString()}; await db.batch([save(owner,a),record(owner,id,'Audit created')]); return Response.json({ok:true,id}); }
 const a=await getAudit(owner,clean(p.auditId,100)); const original=a?JSON.stringify(a):''; if(!a) return Response.json({error:'Audit not found.'},{status:404});
 let description='';
 if(p.action==='status') { const next=statuses.indexOf(p.status||''),current=statuses.indexOf(a.status); if(next!==current+1) return Response.json({error:'Advance one stage at a time.'},{status:409}); if(p.status==='Issued'&&a.findings.some(f=>!f.approved||!f.evidenceId)) return Response.json({error:'Approve all findings and link supporting evidence before issuing the report.'},{status:409}); if(p.status==='Closed'&&a.findings.some(f=>!f.response)) return Response.json({error:'Record a response for every finding before closing the audit.'},{status:409}); a.status=p.status!; description=`Audit moved to ${p.status}`; }
 else if(p.action==='finding') { if(['Issued','Closed'].includes(a.status)) return Response.json({error:'Findings are locked after report issue.'},{status:409}); const title=clean(p.title,200),condition=clean(p.condition),recommendation=clean(p.recommendation); if(!title||!condition||!recommendation||!['Critical','High','Medium','Low'].includes(p.severity||'')) return Response.json({error:'Complete the finding, observation and recommendation.'},{status:400}); const evidenceId=clean(p.evidenceId,100); if(evidenceId&&!await db.prepare('SELECT id FROM audit_evidence WHERE id=? AND audit_id=? AND owner=?').bind(evidenceId,a.id,owner).first()) return Response.json({error:'Select evidence from this audit.'},{status:400}); a.findings.push({id:crypto.randomUUID(),title,severity:p.severity!,condition,recommendation,evidenceId,response:'',approved:false,due:clean(p.due,10)}); description=`Finding recorded: ${title}`; }
 else if(p.action==='respond'||p.action==='approve') { const f=a.findings.find(f=>f.id===p.findingId); if(!f) return Response.json({error:'Finding not found.'},{status:404}); if(a.status==='Closed') return Response.json({error:'This audit is closed.'},{status:409}); if(p.action==='approve') { if(a.status==='Issued') return Response.json({error:'Approval is locked after issue.'},{status:409}); if(!f.evidenceId) return Response.json({error:'Link evidence before approval.'},{status:409}); f.approved=true; description=`Finding approved: ${f.title}`; } else { f.response=clean(p.response); if(!f.response) return Response.json({error:'Enter the institution response.'},{status:400}); description=`Response recorded: ${f.title}`; } }
 else if(p.action==='link') { if(['Issued','Closed'].includes(a.status)) return Response.json({error:'Evidence links are locked after issue.'},{status:409}); const f=a.findings.find(f=>f.id===p.findingId); if(!f||!await db.prepare('SELECT id FROM audit_evidence WHERE id=? AND audit_id=? AND owner=?').bind(p.evidenceId||'',a.id,owner).first()) return Response.json({error:'Select a valid finding and evidence file.'},{status:400}); f.evidenceId=p.evidenceId!;f.approved=false;description=`Supporting evidence linked: ${f.title}`; }
 else return Response.json({error:'Unknown action.'},{status:400});
 const results=await db.batch([db.prepare('UPDATE audit_cases SET data=?,updated=? WHERE id=? AND owner=? AND data=?').bind(JSON.stringify(a),new Date().toISOString(),a.id,owner,original),db.prepare('INSERT INTO audit_events (id,owner,audit_id,description,created) SELECT ?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),owner,a.id,description,new Date().toISOString())]); if(!results[0].meta.changes)return Response.json({error:'This audit changed in another session. Reload before saving again.'},{status:409});return Response.json({ok:true});
 } catch(e) { console.error(e); return Response.json({error:'The change could not be saved. Your input is still available; please retry.'},{status:503}); } }
